// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: common/common_public.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bool status = 1;
	Msg           string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg" jsonschema_description:"bool status = 1;"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResp) Reset() {
	*x = ResultResp{}
	mi := &file_common_common_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResp) ProtoMessage() {}

func (x *ResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResp.ProtoReflect.Descriptor instead.
func (*ResultResp) Descriptor() ([]byte, []int) {
	return file_common_common_public_proto_rawDescGZIP(), []int{0}
}

func (x *ResultResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_common_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_common_public_proto_rawDescGZIP(), []int{1}
}

type SimpSharInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code" jsonschema_description:"当前代码"`           // 当前代码
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name" jsonschema_description:"当前名字"`           // 当前名字
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price" jsonschema_description:"当前指数"`       // 当前指数
	Percent       float64                `protobuf:"fixed64,4,opt,name=percent,proto3" json:"percent" jsonschema_description:"当前涨跌比例"` // 当前涨跌比例
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color" jsonschema_description:"颜色"`           // 颜色
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url" jsonschema_description:"地址"`               // 地址
	Item          *SimpSharInfo          `protobuf:"bytes,7,opt,name=item,proto3" json:"item" jsonschema_description:"子项"`             // 子项
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpSharInfo) Reset() {
	*x = SimpSharInfo{}
	mi := &file_common_common_public_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpSharInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpSharInfo) ProtoMessage() {}

func (x *SimpSharInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_public_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpSharInfo.ProtoReflect.Descriptor instead.
func (*SimpSharInfo) Descriptor() ([]byte, []int) {
	return file_common_common_public_proto_rawDescGZIP(), []int{2}
}

func (x *SimpSharInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SimpSharInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpSharInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SimpSharInfo) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *SimpSharInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *SimpSharInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SimpSharInfo) GetItem() *SimpSharInfo {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_common_common_public_proto protoreflect.FileDescriptor

const file_common_common_public_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/common_public.proto\x12\x06common\"\x1e\n" +
	"\n" +
	"ResultResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\a\n" +
	"\x05Empty\"\xb8\x01\n" +
	"\fSimpSharInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x18\n" +
	"\apercent\x18\x04 \x01(\x01R\apercent\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12(\n" +
	"\x04item\x18\a \x01(\v2\x14.common.SimpSharInfoR\x04itemB\fZ\n" +
	"rpc/commonb\x06proto3"

var (
	file_common_common_public_proto_rawDescOnce sync.Once
	file_common_common_public_proto_rawDescData []byte
)

func file_common_common_public_proto_rawDescGZIP() []byte {
	file_common_common_public_proto_rawDescOnce.Do(func() {
		file_common_common_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_public_proto_rawDesc), len(file_common_common_public_proto_rawDesc)))
	})
	return file_common_common_public_proto_rawDescData
}

var file_common_common_public_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_common_public_proto_goTypes = []any{
	(*ResultResp)(nil),   // 0: common.ResultResp
	(*Empty)(nil),        // 1: common.Empty
	(*SimpSharInfo)(nil), // 2: common.SimpSharInfo
}
var file_common_common_public_proto_depIdxs = []int32{
	2, // 0: common.SimpSharInfo.item:type_name -> common.SimpSharInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_common_public_proto_init() }
func file_common_common_public_proto_init() {
	if File_common_common_public_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_public_proto_rawDesc), len(file_common_common_public_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_public_proto_goTypes,
		DependencyIndexes: file_common_common_public_proto_depIdxs,
		MessageInfos:      file_common_common_public_proto_msgTypes,
	}.Build()
	File_common_common_public_proto = out.File
	file_common_common_public_proto_goTypes = nil
	file_common_common_public_proto_depIdxs = nil
}
