// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v5.29.2
// source: shares/agent.proto

package shares

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	_ "rpc/common"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SearchsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query"` // 搜索关键字
}

func (x *SearchsReq) Reset() {
	*x = SearchsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shares_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchsReq) ProtoMessage() {}

func (x *SearchsReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchsReq.ProtoReflect.Descriptor instead.
func (*SearchsReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{0}
}

func (x *SearchsReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Days int32    `protobuf:"varint,1,opt,name=days,proto3" json:"days"` // 搜索范围，单位为天，(近几天)
	Tags []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags"`  // 要搜索的类型标签，如：黄金上穿、北向、优选日、股息率、机会榜、复利k线
	Hys  []string `protobuf:"bytes,3,rep,name=hys,proto3" json:"hys"`    // 行业列表
	Top  int32    `protobuf:"varint,4,opt,name=top,proto3" json:"top"`   // 返回前几个
}

func (x *SearchCodeReq) Reset() {
	*x = SearchCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shares_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCodeReq) ProtoMessage() {}

func (x *SearchCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCodeReq.ProtoReflect.Descriptor instead.
func (*SearchCodeReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SearchCodeReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *SearchCodeReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchCodeReq) GetHys() []string {
	if x != nil {
		return x.Hys
	}
	return nil
}

func (x *SearchCodeReq) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

type SearchMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Days  int32    `protobuf:"varint,1,opt,name=days,proto3" json:"days"`  // 搜索范围，单位为天，(近几天)
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names"` // 名字:可以是股票名字，行业板块名字，或者什么都不填(整体市场)
	Top   int32    `protobuf:"varint,3,opt,name=top,proto3" json:"top"`    // 分析的总消息数
}

func (x *SearchMsgReq) Reset() {
	*x = SearchMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shares_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMsgReq) ProtoMessage() {}

func (x *SearchMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMsgReq.ProtoReflect.Descriptor instead.
func (*SearchMsgReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMsgReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *SearchMsgReq) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *SearchMsgReq) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

type SearchCodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg"`   // 提示信息
	Docs []string `protobuf:"bytes,2,rep,name=docs,proto3" json:"docs"` // 详细数据
}

func (x *SearchCodeResp) Reset() {
	*x = SearchCodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shares_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCodeResp) ProtoMessage() {}

func (x *SearchCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCodeResp.ProtoReflect.Descriptor instead.
func (*SearchCodeResp) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SearchCodeResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchCodeResp) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

type SearchHyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names"` // 行业名字
}

func (x *SearchHyReq) Reset() {
	*x = SearchHyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shares_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchHyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHyReq) ProtoMessage() {}

func (x *SearchHyReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHyReq.ProtoReflect.Descriptor instead.
func (*SearchHyReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SearchHyReq) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SearchHyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg"`   // 提示信息
	Docs []string `protobuf:"bytes,2,rep,name=docs,proto3" json:"docs"` // 详细数据
}

func (x *SearchHyResp) Reset() {
	*x = SearchHyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shares_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchHyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHyResp) ProtoMessage() {}

func (x *SearchHyResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHyResp.ProtoReflect.Descriptor instead.
func (*SearchHyResp) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SearchHyResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchHyResp) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

type SearchCodeInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codes []string `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes"` // 股票代码
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names"` // 股票名字
}

func (x *SearchCodeInfoReq) Reset() {
	*x = SearchCodeInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shares_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCodeInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCodeInfoReq) ProtoMessage() {}

func (x *SearchCodeInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCodeInfoReq.ProtoReflect.Descriptor instead.
func (*SearchCodeInfoReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SearchCodeInfoReq) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *SearchCodeInfoReq) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SearchCodeinfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg"`   // 提示信息
	Docs []string `protobuf:"bytes,2,rep,name=docs,proto3" json:"docs"` // 详细数据
}

func (x *SearchCodeinfoResp) Reset() {
	*x = SearchCodeinfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shares_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCodeinfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCodeinfoResp) ProtoMessage() {}

func (x *SearchCodeinfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCodeinfoResp.ProtoReflect.Descriptor instead.
func (*SearchCodeinfoResp) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SearchCodeinfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchCodeinfoResp) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

type ChatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg       string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg"`             // 搜索关键字
	SessionId string   `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId"` // 会话id
	Key       string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key"`             // 技能id
	Think     bool     `protobuf:"varint,4,opt,name=think,proto3" json:"think"`
	Attach    []string `protobuf:"bytes,5,rep,name=attach,proto3" json:"attach"` // 附件
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shares_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ChatReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ChatReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChatReq) GetThink() bool {
	if x != nil {
		return x.Think
	}
	return false
}

func (x *ChatReq) GetAttach() []string {
	if x != nil {
		return x.Attach
	}
	return nil
}

type ChatKv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
}

func (x *ChatKv) Reset() {
	*x = ChatKv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shares_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatKv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatKv) ProtoMessage() {}

func (x *ChatKv) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatKv.ProtoReflect.Descriptor instead.
func (*ChatKv) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ChatKv) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChatKv) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ChatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ChatKv `protobuf:"bytes,1,rep,name=list,proto3" json:"list"` // 详细数据
}

func (x *ChatResp) Reset() {
	*x = ChatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shares_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResp) ProtoMessage() {}

func (x *ChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResp.ProtoReflect.Descriptor instead.
func (*ChatResp) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ChatResp) GetList() []*ChatKv {
	if x != nil {
		return x.List
	}
	return nil
}

var File_shares_agent_proto protoreflect.FileDescriptor

var file_shares_agent_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x1a, 0x1a, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x5b, 0x0a, 0x0d,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x79, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x61, 0x79,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x68, 0x79, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x6f, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x6f, 0x70, 0x22, 0x4a, 0x0a, 0x0c, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x79,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x61, 0x79, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x74, 0x6f, 0x70, 0x22, 0x36, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x63,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x22, 0x23, 0x0a,
	0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x79, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x22, 0x34, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x22, 0x3f, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f,
	0x64, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x12, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x6f, 0x63, 0x73, 0x22, 0x79, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x74, 0x68, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x22, 0x30, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x74, 0x4b, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x2e, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4b, 0x76, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x32, 0x83, 0x02, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x49, 0x0a, 0x0e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f,
	0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x69, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x48, 0x79, 0x12, 0x13, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x48, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x3d, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x15,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x37, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x73, 0x12, 0x12, 0x2e, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x72, 0x70, 0x63, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shares_agent_proto_rawDescOnce sync.Once
	file_shares_agent_proto_rawDescData = file_shares_agent_proto_rawDesc
)

func file_shares_agent_proto_rawDescGZIP() []byte {
	file_shares_agent_proto_rawDescOnce.Do(func() {
		file_shares_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_shares_agent_proto_rawDescData)
	})
	return file_shares_agent_proto_rawDescData
}

var file_shares_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_shares_agent_proto_goTypes = []interface{}{
	(*SearchsReq)(nil),         // 0: shares.SearchsReq
	(*SearchCodeReq)(nil),      // 1: shares.SearchCodeReq
	(*SearchMsgReq)(nil),       // 2: shares.SearchMsgReq
	(*SearchCodeResp)(nil),     // 3: shares.SearchCodeResp
	(*SearchHyReq)(nil),        // 4: shares.SearchHyReq
	(*SearchHyResp)(nil),       // 5: shares.SearchHyResp
	(*SearchCodeInfoReq)(nil),  // 6: shares.SearchCodeInfoReq
	(*SearchCodeinfoResp)(nil), // 7: shares.SearchCodeinfoResp
	(*ChatReq)(nil),            // 8: shares.ChatReq
	(*ChatKv)(nil),             // 9: shares.ChatKv
	(*ChatResp)(nil),           // 10: shares.ChatResp
}
var file_shares_agent_proto_depIdxs = []int32{
	9, // 0: shares.ChatResp.list:type_name -> shares.ChatKv
	6, // 1: shares.agent.SearchCodeInfo:input_type -> shares.SearchCodeInfoReq
	4, // 2: shares.agent.SearchHy:input_type -> shares.SearchHyReq
	1, // 3: shares.agent.SearchCode:input_type -> shares.SearchCodeReq
	0, // 4: shares.agent.Searchs:input_type -> shares.SearchsReq
	7, // 5: shares.agent.SearchCodeInfo:output_type -> shares.SearchCodeinfoResp
	5, // 6: shares.agent.SearchHy:output_type -> shares.SearchHyResp
	3, // 7: shares.agent.SearchCode:output_type -> shares.SearchCodeResp
	3, // 8: shares.agent.Searchs:output_type -> shares.SearchCodeResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shares_agent_proto_init() }
func file_shares_agent_proto_init() {
	if File_shares_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shares_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shares_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shares_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shares_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shares_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchHyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shares_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchHyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shares_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCodeInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shares_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCodeinfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shares_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shares_agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatKv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shares_agent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shares_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shares_agent_proto_goTypes,
		DependencyIndexes: file_shares_agent_proto_depIdxs,
		MessageInfos:      file_shares_agent_proto_msgTypes,
	}.Build()
	File_shares_agent_proto = out.File
	file_shares_agent_proto_rawDesc = nil
	file_shares_agent_proto_goTypes = nil
	file_shares_agent_proto_depIdxs = nil
}
