// Code generated by protoc-gen-gmsec. DO NOT EDIT.

package shares

// Tool descriptions from proto comments
const (
	// 获取股票详情
	Agent_SearchCodeInfo_ToolDesc = "获取股票详情"
	// 获取股票详情
	Agent_SearchHy_ToolDesc = "获取股票详情"
	// 通过类型搜索股票代码
	Agent_SearchCode_ToolDesc = "通过类型搜索股票代码"
	// 通过类型搜索股票代码
	Agent_Searchs_ToolDesc = "通过类型搜索股票代码"
)
