// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: shares/agent.proto

package shares

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	_ "rpc/common"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query"` // 搜索关键字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchsReq) Reset() {
	*x = SearchsReq{}
	mi := &file_shares_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchsReq) ProtoMessage() {}

func (x *SearchsReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchsReq.ProtoReflect.Descriptor instead.
func (*SearchsReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{0}
}

func (x *SearchsReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days"` // 搜索范围，单位为天，(近几天)
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags"`  // 要搜索的类型标签，如：黄金上穿、北向、优选日、股息率、机会榜、复利k线
	Hys           []string               `protobuf:"bytes,3,rep,name=hys,proto3" json:"hys"`    // 行业列表
	Top           int32                  `protobuf:"varint,4,opt,name=top,proto3" json:"top"`   // 返回前几个
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCodeReq) Reset() {
	*x = SearchCodeReq{}
	mi := &file_shares_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCodeReq) ProtoMessage() {}

func (x *SearchCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCodeReq.ProtoReflect.Descriptor instead.
func (*SearchCodeReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SearchCodeReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *SearchCodeReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchCodeReq) GetHys() []string {
	if x != nil {
		return x.Hys
	}
	return nil
}

func (x *SearchCodeReq) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

type SearchMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days"`  // 搜索范围，单位为天，(近几天)
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names"` // 名字:可以是股票名字，行业板块名字，或者什么都不填(整体市场)
	Top           int32                  `protobuf:"varint,3,opt,name=top,proto3" json:"top"`    // 分析的总消息数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMsgReq) Reset() {
	*x = SearchMsgReq{}
	mi := &file_shares_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMsgReq) ProtoMessage() {}

func (x *SearchMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMsgReq.ProtoReflect.Descriptor instead.
func (*SearchMsgReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMsgReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *SearchMsgReq) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *SearchMsgReq) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

type SearchCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg"`   // 提示信息
	Docs          []string               `protobuf:"bytes,2,rep,name=docs,proto3" json:"docs"` // 详细数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCodeResp) Reset() {
	*x = SearchCodeResp{}
	mi := &file_shares_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCodeResp) ProtoMessage() {}

func (x *SearchCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCodeResp.ProtoReflect.Descriptor instead.
func (*SearchCodeResp) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SearchCodeResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchCodeResp) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

type SearchHyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names"` // 行业名字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHyReq) Reset() {
	*x = SearchHyReq{}
	mi := &file_shares_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHyReq) ProtoMessage() {}

func (x *SearchHyReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHyReq.ProtoReflect.Descriptor instead.
func (*SearchHyReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SearchHyReq) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SearchHyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg"`   // 提示信息
	Docs          []string               `protobuf:"bytes,2,rep,name=docs,proto3" json:"docs"` // 详细数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHyResp) Reset() {
	*x = SearchHyResp{}
	mi := &file_shares_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHyResp) ProtoMessage() {}

func (x *SearchHyResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHyResp.ProtoReflect.Descriptor instead.
func (*SearchHyResp) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SearchHyResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchHyResp) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

type SearchCodeInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes"` // 股票代码
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names"` // 股票名字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCodeInfoReq) Reset() {
	*x = SearchCodeInfoReq{}
	mi := &file_shares_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCodeInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCodeInfoReq) ProtoMessage() {}

func (x *SearchCodeInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCodeInfoReq.ProtoReflect.Descriptor instead.
func (*SearchCodeInfoReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SearchCodeInfoReq) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *SearchCodeInfoReq) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SearchCodeinfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg"`   // 提示信息
	Docs          []string               `protobuf:"bytes,2,rep,name=docs,proto3" json:"docs"` // 详细数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCodeinfoResp) Reset() {
	*x = SearchCodeinfoResp{}
	mi := &file_shares_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCodeinfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCodeinfoResp) ProtoMessage() {}

func (x *SearchCodeinfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCodeinfoResp.ProtoReflect.Descriptor instead.
func (*SearchCodeinfoResp) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SearchCodeinfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SearchCodeinfoResp) GetDocs() []string {
	if x != nil {
		return x.Docs
	}
	return nil
}

type ChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg"`             // 搜索关键字
	SessionId     string                 `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId"` // 会话id
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key"`             // 技能id
	Think         bool                   `protobuf:"varint,4,opt,name=think,proto3" json:"think"`
	Attach        []string               `protobuf:"bytes,5,rep,name=attach,proto3" json:"attach"` // 附件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_shares_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ChatReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ChatReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChatReq) GetThink() bool {
	if x != nil {
		return x.Think
	}
	return false
}

func (x *ChatReq) GetAttach() []string {
	if x != nil {
		return x.Attach
	}
	return nil
}

type ChatKv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatKv) Reset() {
	*x = ChatKv{}
	mi := &file_shares_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatKv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatKv) ProtoMessage() {}

func (x *ChatKv) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatKv.ProtoReflect.Descriptor instead.
func (*ChatKv) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ChatKv) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChatKv) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ChatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ChatKv              `protobuf:"bytes,1,rep,name=list,proto3" json:"list"` // 详细数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResp) Reset() {
	*x = ChatResp{}
	mi := &file_shares_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResp) ProtoMessage() {}

func (x *ChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResp.ProtoReflect.Descriptor instead.
func (*ChatResp) Descriptor() ([]byte, []int) {
	return file_shares_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ChatResp) GetList() []*ChatKv {
	if x != nil {
		return x.List
	}
	return nil
}

var File_shares_agent_proto protoreflect.FileDescriptor

const file_shares_agent_proto_rawDesc = "" +
	"\n" +
	"\x12shares/agent.proto\x12\x06shares\x1a\x1acommon/common_public.proto\"\"\n" +
	"\n" +
	"SearchsReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"[\n" +
	"\rSearchCodeReq\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x10\n" +
	"\x03hys\x18\x03 \x03(\tR\x03hys\x12\x10\n" +
	"\x03top\x18\x04 \x01(\x05R\x03top\"J\n" +
	"\fSearchMsgReq\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12\x10\n" +
	"\x03top\x18\x03 \x01(\x05R\x03top\"6\n" +
	"\x0eSearchCodeResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04docs\x18\x02 \x03(\tR\x04docs\"#\n" +
	"\vSearchHyReq\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\"4\n" +
	"\fSearchHyResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04docs\x18\x02 \x03(\tR\x04docs\"?\n" +
	"\x11SearchCodeInfoReq\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\":\n" +
	"\x12SearchCodeinfoResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04docs\x18\x02 \x03(\tR\x04docs\"y\n" +
	"\aChatReq\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1c\n" +
	"\tsessionId\x18\x02 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05think\x18\x04 \x01(\bR\x05think\x12\x16\n" +
	"\x06attach\x18\x05 \x03(\tR\x06attach\"0\n" +
	"\x06ChatKv\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\".\n" +
	"\bChatResp\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.shares.ChatKvR\x04list2\x83\x02\n" +
	"\x05agent\x12I\n" +
	"\x0eSearchCodeInfo\x12\x19.shares.SearchCodeInfoReq\x1a\x1a.shares.SearchCodeinfoResp\"\x00\x127\n" +
	"\bSearchHy\x12\x13.shares.SearchHyReq\x1a\x14.shares.SearchHyResp\"\x00\x12=\n" +
	"\n" +
	"SearchCode\x12\x15.shares.SearchCodeReq\x1a\x16.shares.SearchCodeResp\"\x00\x127\n" +
	"\aSearchs\x12\x12.shares.SearchsReq\x1a\x16.shares.SearchCodeResp\"\x00B\fZ\n" +
	"rpc/sharesb\x06proto3"

var (
	file_shares_agent_proto_rawDescOnce sync.Once
	file_shares_agent_proto_rawDescData []byte
)

func file_shares_agent_proto_rawDescGZIP() []byte {
	file_shares_agent_proto_rawDescOnce.Do(func() {
		file_shares_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shares_agent_proto_rawDesc), len(file_shares_agent_proto_rawDesc)))
	})
	return file_shares_agent_proto_rawDescData
}

var file_shares_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_shares_agent_proto_goTypes = []any{
	(*SearchsReq)(nil),         // 0: shares.SearchsReq
	(*SearchCodeReq)(nil),      // 1: shares.SearchCodeReq
	(*SearchMsgReq)(nil),       // 2: shares.SearchMsgReq
	(*SearchCodeResp)(nil),     // 3: shares.SearchCodeResp
	(*SearchHyReq)(nil),        // 4: shares.SearchHyReq
	(*SearchHyResp)(nil),       // 5: shares.SearchHyResp
	(*SearchCodeInfoReq)(nil),  // 6: shares.SearchCodeInfoReq
	(*SearchCodeinfoResp)(nil), // 7: shares.SearchCodeinfoResp
	(*ChatReq)(nil),            // 8: shares.ChatReq
	(*ChatKv)(nil),             // 9: shares.ChatKv
	(*ChatResp)(nil),           // 10: shares.ChatResp
}
var file_shares_agent_proto_depIdxs = []int32{
	9, // 0: shares.ChatResp.list:type_name -> shares.ChatKv
	6, // 1: shares.agent.SearchCodeInfo:input_type -> shares.SearchCodeInfoReq
	4, // 2: shares.agent.SearchHy:input_type -> shares.SearchHyReq
	1, // 3: shares.agent.SearchCode:input_type -> shares.SearchCodeReq
	0, // 4: shares.agent.Searchs:input_type -> shares.SearchsReq
	7, // 5: shares.agent.SearchCodeInfo:output_type -> shares.SearchCodeinfoResp
	5, // 6: shares.agent.SearchHy:output_type -> shares.SearchHyResp
	3, // 7: shares.agent.SearchCode:output_type -> shares.SearchCodeResp
	3, // 8: shares.agent.Searchs:output_type -> shares.SearchCodeResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shares_agent_proto_init() }
func file_shares_agent_proto_init() {
	if File_shares_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shares_agent_proto_rawDesc), len(file_shares_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shares_agent_proto_goTypes,
		DependencyIndexes: file_shares_agent_proto_depIdxs,
		MessageInfos:      file_shares_agent_proto_msgTypes,
	}.Build()
	File_shares_agent_proto = out.File
	file_shares_agent_proto_goTypes = nil
	file_shares_agent_proto_depIdxs = nil
}
