// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: shares/analy.proto

package shares

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	common "rpc/common"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCjrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCjrlReq) Reset() {
	*x = GetCjrlReq{}
	mi := &file_shares_analy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCjrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCjrlReq) ProtoMessage() {}

func (x *GetCjrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCjrlReq.ProtoReflect.Descriptor instead.
func (*GetCjrlReq) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{0}
}

func (x *GetCjrlReq) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type GetCjrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jjsj          []*JjrbInfo            `protobuf:"bytes,1,rep,name=jjsj,proto3" json:"jjsj" jsonschema_description:"经济数据"` // 经济数据
	Sj            []*JjrbInfo            `protobuf:"bytes,2,rep,name=sj,proto3" json:"sj" jsonschema_description:"事件"`       // 事件
	Hy            []*JjrbInfo            `protobuf:"bytes,3,rep,name=hy,proto3" json:"hy" jsonschema_description:"会议"`       // 会议
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCjrlResp) Reset() {
	*x = GetCjrlResp{}
	mi := &file_shares_analy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCjrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCjrlResp) ProtoMessage() {}

func (x *GetCjrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCjrlResp.ProtoReflect.Descriptor instead.
func (*GetCjrlResp) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{1}
}

func (x *GetCjrlResp) GetJjsj() []*JjrbInfo {
	if x != nil {
		return x.Jjsj
	}
	return nil
}

func (x *GetCjrlResp) GetSj() []*JjrbInfo {
	if x != nil {
		return x.Sj
	}
	return nil
}

func (x *GetCjrlResp) GetHy() []*JjrbInfo {
	if x != nil {
		return x.Hy
	}
	return nil
}

type GetGjzbResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GjzbInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list" jsonschema_description:"列表"` // 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGjzbResp) Reset() {
	*x = GetGjzbResp{}
	mi := &file_shares_analy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGjzbResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGjzbResp) ProtoMessage() {}

func (x *GetGjzbResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGjzbResp.ProtoReflect.Descriptor instead.
func (*GetGjzbResp) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{2}
}

func (x *GetGjzbResp) GetList() []*GjzbInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GjzbInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price" jsonschema_description:"当前指数"`          // 当前指数
	Percent       float64                `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent" jsonschema_description:"当前涨跌比例"`    // 当前涨跌比例
	ChangeNum     float64                `protobuf:"fixed64,3,opt,name=changeNum,proto3" json:"changeNum" jsonschema_description:"当前涨跌数"` // 当前涨跌数
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code" jsonschema_description:"当前代码"`              // 当前代码
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name" jsonschema_description:"当前名字"`              // 当前名字
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color" jsonschema_description:"颜色"`              // 颜色
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GjzbInfo) Reset() {
	*x = GjzbInfo{}
	mi := &file_shares_analy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GjzbInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GjzbInfo) ProtoMessage() {}

func (x *GjzbInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GjzbInfo.ProtoReflect.Descriptor instead.
func (*GjzbInfo) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{3}
}

func (x *GjzbInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GjzbInfo) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *GjzbInfo) GetChangeNum() float64 {
	if x != nil {
		return x.ChangeNum
	}
	return 0
}

func (x *GjzbInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GjzbInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GjzbInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type GetSampleWdjReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hexinv        string                 `protobuf:"bytes,1,opt,name=hexinv,proto3" json:"hexinv"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleWdjReq) Reset() {
	*x = GetSampleWdjReq{}
	mi := &file_shares_analy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleWdjReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleWdjReq) ProtoMessage() {}

func (x *GetSampleWdjReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleWdjReq.ProtoReflect.Descriptor instead.
func (*GetSampleWdjReq) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{4}
}

func (x *GetSampleWdjReq) GetHexinv() string {
	if x != nil {
		return x.Hexinv
	}
	return ""
}

type GetSampleWdjResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseHeat      float64                `protobuf:"fixed64,1,opt,name=baseHeat,proto3" json:"baseHeat" jsonschema_description:"基础温度"` // 基础温度
	DayHeat       float64                `protobuf:"fixed64,2,opt,name=dayHeat,proto3" json:"dayHeat" jsonschema_description:"当日温度"`   // 当日温度
	Rg            bool                   `protobuf:"varint,3,opt,name=rg,proto3" json:"rg" jsonschema_description:"是否红涨绿跌"`            // 是否红涨绿跌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleWdjResp) Reset() {
	*x = GetSampleWdjResp{}
	mi := &file_shares_analy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleWdjResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleWdjResp) ProtoMessage() {}

func (x *GetSampleWdjResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleWdjResp.ProtoReflect.Descriptor instead.
func (*GetSampleWdjResp) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{5}
}

func (x *GetSampleWdjResp) GetBaseHeat() float64 {
	if x != nil {
		return x.BaseHeat
	}
	return 0
}

func (x *GetSampleWdjResp) GetDayHeat() float64 {
	if x != nil {
		return x.DayHeat
	}
	return 0
}

func (x *GetSampleWdjResp) GetRg() bool {
	if x != nil {
		return x.Rg
	}
	return false
}

// AnalyCodeReq 请求
type AnalyCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code" jsonschema_description:"股票代码"` // 股票代码
	Len           int32                  `protobuf:"varint,2,opt,name=len,proto3" json:"len"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyCodeReq) Reset() {
	*x = AnalyCodeReq{}
	mi := &file_shares_analy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyCodeReq) ProtoMessage() {}

func (x *AnalyCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyCodeReq.ProtoReflect.Descriptor instead.
func (*AnalyCodeReq) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{6}
}

func (x *AnalyCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AnalyCodeReq) GetLen() int32 {
	if x != nil {
		return x.Len
	}
	return 0
}

// AnalyCodeResp 返回
type AnalyCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AnalyCodeInfo       `protobuf:"bytes,1,rep,name=list,proto3" json:"list" jsonschema_description:"内容"` // 内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyCodeResp) Reset() {
	*x = AnalyCodeResp{}
	mi := &file_shares_analy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyCodeResp) ProtoMessage() {}

func (x *AnalyCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyCodeResp.ProtoReflect.Descriptor instead.
func (*AnalyCodeResp) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{7}
}

func (x *AnalyCodeResp) GetList() []*AnalyCodeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type AnalyCodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name" jsonschema_description:"名字"` // 名字
	Msgs          []string               `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs" jsonschema_description:"内容"` // 内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyCodeInfo) Reset() {
	*x = AnalyCodeInfo{}
	mi := &file_shares_analy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyCodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyCodeInfo) ProtoMessage() {}

func (x *AnalyCodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyCodeInfo.ProtoReflect.Descriptor instead.
func (*AnalyCodeInfo) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{8}
}

func (x *AnalyCodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnalyCodeInfo) GetMsgs() []string {
	if x != nil {
		return x.Msgs
	}
	return nil
}

// GetAllSpReq 请求
type GetAllSpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code" jsonschema_description:"股票代码"` // 股票代码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSpReq) Reset() {
	*x = GetAllSpReq{}
	mi := &file_shares_analy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSpReq) ProtoMessage() {}

func (x *GetAllSpReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSpReq.ProtoReflect.Descriptor instead.
func (*GetAllSpReq) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllSpReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SpShowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	D1            string                 `protobuf:"bytes,1,opt,name=d1,proto3" json:"d1" jsonschema_description:"名字"`       // 名字
	D2            string                 `protobuf:"bytes,2,opt,name=d2,proto3" json:"d2" jsonschema_description:"发布日"`      // 发布日
	D3            string                 `protobuf:"bytes,3,opt,name=d3,proto3" json:"d3" jsonschema_description:"数量"`       // 数量
	D4            string                 `protobuf:"bytes,4,opt,name=d4,proto3" json:"d4" jsonschema_description:"描述"`       // 描述
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color" jsonschema_description:"颜色"` // 颜色
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpShowInfo) Reset() {
	*x = SpShowInfo{}
	mi := &file_shares_analy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpShowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpShowInfo) ProtoMessage() {}

func (x *SpShowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpShowInfo.ProtoReflect.Descriptor instead.
func (*SpShowInfo) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{10}
}

func (x *SpShowInfo) GetD1() string {
	if x != nil {
		return x.D1
	}
	return ""
}

func (x *SpShowInfo) GetD2() string {
	if x != nil {
		return x.D2
	}
	return ""
}

func (x *SpShowInfo) GetD3() string {
	if x != nil {
		return x.D3
	}
	return ""
}

func (x *SpShowInfo) GetD4() string {
	if x != nil {
		return x.D4
	}
	return ""
}

func (x *SpShowInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type AllSpInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title" jsonschema_description:"标签"`    // 标签
	D1            string                 `protobuf:"bytes,2,opt,name=d1,proto3" json:"d1" jsonschema_description:"名字"`          // 名字
	D2            string                 `protobuf:"bytes,3,opt,name=d2,proto3" json:"d2" jsonschema_description:"发布日"`         // 发布日
	D3            string                 `protobuf:"bytes,4,opt,name=d3,proto3" json:"d3" jsonschema_description:"数量"`          // 数量
	D4            string                 `protobuf:"bytes,5,opt,name=d4,proto3" json:"d4" jsonschema_description:"描述"`          // 描述
	IsDot         bool                   `protobuf:"varint,6,opt,name=isDot,proto3" json:"isDot" jsonschema_description:"是否推荐"` // 是否推荐
	List          []*SpShowInfo          `protobuf:"bytes,7,rep,name=list,proto3" json:"list" jsonschema_description:"列表"`      // 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllSpInfo) Reset() {
	*x = AllSpInfo{}
	mi := &file_shares_analy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllSpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllSpInfo) ProtoMessage() {}

func (x *AllSpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllSpInfo.ProtoReflect.Descriptor instead.
func (*AllSpInfo) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{11}
}

func (x *AllSpInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AllSpInfo) GetD1() string {
	if x != nil {
		return x.D1
	}
	return ""
}

func (x *AllSpInfo) GetD2() string {
	if x != nil {
		return x.D2
	}
	return ""
}

func (x *AllSpInfo) GetD3() string {
	if x != nil {
		return x.D3
	}
	return ""
}

func (x *AllSpInfo) GetD4() string {
	if x != nil {
		return x.D4
	}
	return ""
}

func (x *AllSpInfo) GetIsDot() bool {
	if x != nil {
		return x.IsDot
	}
	return false
}

func (x *AllSpInfo) GetList() []*SpShowInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type BaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color"`
	Name1         string                 `protobuf:"bytes,4,opt,name=name1,proto3" json:"name1"`
	Value1        string                 `protobuf:"bytes,5,opt,name=value1,proto3" json:"value1"`
	Color1        string                 `protobuf:"bytes,6,opt,name=color1,proto3" json:"color1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfo) Reset() {
	*x = BaseInfo{}
	mi := &file_shares_analy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfo) ProtoMessage() {}

func (x *BaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfo.ProtoReflect.Descriptor instead.
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{12}
}

func (x *BaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BaseInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *BaseInfo) GetName1() string {
	if x != nil {
		return x.Name1
	}
	return ""
}

func (x *BaseInfo) GetValue1() string {
	if x != nil {
		return x.Value1
	}
	return ""
}

func (x *BaseInfo) GetColor1() string {
	if x != nil {
		return x.Color1
	}
	return ""
}

// GetAllSpResp
type GetAllSpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AllSpInfo           `protobuf:"bytes,3,rep,name=list,proto3" json:"list" jsonschema_description:"列表"` // 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSpResp) Reset() {
	*x = GetAllSpResp{}
	mi := &file_shares_analy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSpResp) ProtoMessage() {}

func (x *GetAllSpResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSpResp.ProtoReflect.Descriptor instead.
func (*GetAllSpResp) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllSpResp) GetList() []*AllSpInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GetBaseInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vip           bool                   `protobuf:"varint,1,opt,name=vip,proto3" json:"vip" jsonschema_description:"是否vip"`         // 是否vip
	Token         int32                  `protobuf:"varint,2,opt,name=token,proto3" json:"token" jsonschema_description:"token 数"`   // token 数
	BaseInfo      []*BaseInfo            `protobuf:"bytes,4,rep,name=baseInfo,proto3" json:"baseInfo" jsonschema_description:"基础数据"` // 基础数据
	WgjlUrl       string                 `protobuf:"bytes,5,opt,name=wgjlUrl,proto3" json:"wgjlUrl" jsonschema_description:"违规记录"`   // 违规记录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaseInfoResp) Reset() {
	*x = GetBaseInfoResp{}
	mi := &file_shares_analy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaseInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseInfoResp) ProtoMessage() {}

func (x *GetBaseInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseInfoResp.ProtoReflect.Descriptor instead.
func (*GetBaseInfoResp) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{14}
}

func (x *GetBaseInfoResp) GetVip() bool {
	if x != nil {
		return x.Vip
	}
	return false
}

func (x *GetBaseInfoResp) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *GetBaseInfoResp) GetBaseInfo() []*BaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

func (x *GetBaseInfoResp) GetWgjlUrl() string {
	if x != nil {
		return x.WgjlUrl
	}
	return ""
}

type GetArticInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title"`
	Tm            string                 `protobuf:"bytes,2,opt,name=tm,proto3" json:"tm"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticInfo) Reset() {
	*x = GetArticInfo{}
	mi := &file_shares_analy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticInfo) ProtoMessage() {}

func (x *GetArticInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticInfo.ProtoReflect.Descriptor instead.
func (*GetArticInfo) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{15}
}

func (x *GetArticInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetArticInfo) GetTm() string {
	if x != nil {
		return x.Tm
	}
	return ""
}

type GetArticResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GetArticInfo        `protobuf:"bytes,1,rep,name=list,proto3" json:"list" jsonschema_description:"显示的名字"` // 显示的名字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticResp) Reset() {
	*x = GetArticResp{}
	mi := &file_shares_analy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticResp) ProtoMessage() {}

func (x *GetArticResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticResp.ProtoReflect.Descriptor instead.
func (*GetArticResp) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{16}
}

func (x *GetArticResp) GetList() []*GetArticInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GetBxNxKlineInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Times1        []string               `protobuf:"bytes,10,rep,name=times1,proto3" json:"times1" jsonschema_description:"北向"`            // 北向
	DayStr1       string                 `protobuf:"bytes,11,opt,name=dayStr1,proto3" json:"dayStr1" jsonschema_description:"当天时间"`        // 当天时间
	Bs2           []float64              `protobuf:"fixed64,2,rep,packed,name=bs2,proto3" json:"bs2" jsonschema_description:"沪股通,净买入"`     // 沪股通,净买入
	Bs3           []float64              `protobuf:"fixed64,3,rep,packed,name=bs3,proto3" json:"bs3" jsonschema_description:"深股通,净买入"`     // 深股通,净买入
	Bs4           []float64              `protobuf:"fixed64,4,rep,packed,name=bs4,proto3" json:"bs4" jsonschema_description:"北向资金,净买入"`    // 北向资金,净买入
	Bs5           []float64              `protobuf:"fixed64,5,rep,packed,name=bs5,proto3" json:"bs5" jsonschema_description:"沪股通,净流入"`     // 沪股通,净流入
	Bs6           []float64              `protobuf:"fixed64,6,rep,packed,name=bs6,proto3" json:"bs6" jsonschema_description:"深股通,净流入"`     // 深股通,净流入
	Bs7           []float64              `protobuf:"fixed64,7,rep,packed,name=bs7,proto3" json:"bs7" jsonschema_description:"北向资金,净流入"`    // 北向资金,净流入
	Times2        []string               `protobuf:"bytes,20,rep,name=times2,proto3" json:"times2" jsonschema_description:"南向"`            // 南向
	DayStr2       string                 `protobuf:"bytes,21,opt,name=dayStr2,proto3" json:"dayStr2" jsonschema_description:"当天时间"`        // 当天时间
	Nx2           []float64              `protobuf:"fixed64,22,rep,packed,name=nx2,proto3" json:"nx2" jsonschema_description:"港股通(沪),净流入"` // 港股通(沪),净流入
	Nx3           []float64              `protobuf:"fixed64,23,rep,packed,name=nx3,proto3" json:"nx3" jsonschema_description:"港股通(深),净流入"` // 港股通(深),净流入
	Nx4           []float64              `protobuf:"fixed64,24,rep,packed,name=nx4,proto3" json:"nx4" jsonschema_description:"南向资金,净流入"`   // 南向资金,净流入
	Nx5           []float64              `protobuf:"fixed64,25,rep,packed,name=nx5,proto3" json:"nx5" jsonschema_description:"港股通(沪),净流入"` // 港股通(沪),净流入
	Nx6           []float64              `protobuf:"fixed64,26,rep,packed,name=nx6,proto3" json:"nx6" jsonschema_description:"港股通(深),净流入"` // 港股通(深),净流入
	Nx7           []float64              `protobuf:"fixed64,27,rep,packed,name=nx7,proto3" json:"nx7" jsonschema_description:"南向资金,净流入"`   // 南向资金,净流入
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBxNxKlineInfoResp) Reset() {
	*x = GetBxNxKlineInfoResp{}
	mi := &file_shares_analy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBxNxKlineInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBxNxKlineInfoResp) ProtoMessage() {}

func (x *GetBxNxKlineInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBxNxKlineInfoResp.ProtoReflect.Descriptor instead.
func (*GetBxNxKlineInfoResp) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{17}
}

func (x *GetBxNxKlineInfoResp) GetTimes1() []string {
	if x != nil {
		return x.Times1
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetDayStr1() string {
	if x != nil {
		return x.DayStr1
	}
	return ""
}

func (x *GetBxNxKlineInfoResp) GetBs2() []float64 {
	if x != nil {
		return x.Bs2
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetBs3() []float64 {
	if x != nil {
		return x.Bs3
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetBs4() []float64 {
	if x != nil {
		return x.Bs4
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetBs5() []float64 {
	if x != nil {
		return x.Bs5
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetBs6() []float64 {
	if x != nil {
		return x.Bs6
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetBs7() []float64 {
	if x != nil {
		return x.Bs7
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetTimes2() []string {
	if x != nil {
		return x.Times2
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetDayStr2() string {
	if x != nil {
		return x.DayStr2
	}
	return ""
}

func (x *GetBxNxKlineInfoResp) GetNx2() []float64 {
	if x != nil {
		return x.Nx2
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetNx3() []float64 {
	if x != nil {
		return x.Nx3
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetNx4() []float64 {
	if x != nil {
		return x.Nx4
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetNx5() []float64 {
	if x != nil {
		return x.Nx5
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetNx6() []float64 {
	if x != nil {
		return x.Nx6
	}
	return nil
}

func (x *GetBxNxKlineInfoResp) GetNx7() []float64 {
	if x != nil {
		return x.Nx7
	}
	return nil
}

type JjrbInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country" jsonschema_description:"城市"` // 城市
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Previous      string                 `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous" jsonschema_description:"前值"`   // 前值
	Consensus     string                 `protobuf:"bytes,4,opt,name=consensus,proto3" json:"consensus" jsonschema_description:"预期"` // 预期
	Actual        string                 `protobuf:"bytes,5,opt,name=actual,proto3" json:"actual" jsonschema_description:"实际值"`      // 实际值
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url"`
	Tm            string                 `protobuf:"bytes,7,opt,name=tm,proto3" json:"tm"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JjrbInfo) Reset() {
	*x = JjrbInfo{}
	mi := &file_shares_analy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JjrbInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JjrbInfo) ProtoMessage() {}

func (x *JjrbInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JjrbInfo.ProtoReflect.Descriptor instead.
func (*JjrbInfo) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{18}
}

func (x *JjrbInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *JjrbInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JjrbInfo) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *JjrbInfo) GetConsensus() string {
	if x != nil {
		return x.Consensus
	}
	return ""
}

func (x *JjrbInfo) GetActual() string {
	if x != nil {
		return x.Actual
	}
	return ""
}

func (x *JjrbInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *JjrbInfo) GetTm() string {
	if x != nil {
		return x.Tm
	}
	return ""
}

type MainShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tm            string                 `protobuf:"bytes,1,opt,name=tm,proto3" json:"tm"`
	Price         []float64              `protobuf:"fixed64,2,rep,packed,name=price,proto3" json:"price"`
	Main          []float64              `protobuf:"fixed64,3,rep,packed,name=main,proto3" json:"main" jsonschema_description:"当日主力情况"` // 当日主力情况
	MainDay       float64                `protobuf:"fixed64,4,opt,name=mainDay,proto3" json:"mainDay"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MainShare) Reset() {
	*x = MainShare{}
	mi := &file_shares_analy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MainShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainShare) ProtoMessage() {}

func (x *MainShare) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainShare.ProtoReflect.Descriptor instead.
func (*MainShare) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{19}
}

func (x *MainShare) GetTm() string {
	if x != nil {
		return x.Tm
	}
	return ""
}

func (x *MainShare) GetPrice() []float64 {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *MainShare) GetMain() []float64 {
	if x != nil {
		return x.Main
	}
	return nil
}

func (x *MainShare) GetMainDay() float64 {
	if x != nil {
		return x.MainDay
	}
	return 0
}

type GetGdDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Tag           int32                  `protobuf:"varint,2,opt,name=tag,proto3" json:"tag" jsonschema_description:"0:机构，1：10大流通股东，2:10大股东"` // 0:机构，1：10大流通股东，2:10大股东
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGdDataReq) Reset() {
	*x = GetGdDataReq{}
	mi := &file_shares_analy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGdDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGdDataReq) ProtoMessage() {}

func (x *GetGdDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGdDataReq.ProtoReflect.Descriptor instead.
func (*GetGdDataReq) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{20}
}

func (x *GetGdDataReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetGdDataReq) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

type GetGdDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AllSpInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGdDataResp) Reset() {
	*x = GetGdDataResp{}
	mi := &file_shares_analy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGdDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGdDataResp) ProtoMessage() {}

func (x *GetGdDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGdDataResp.ProtoReflect.Descriptor instead.
func (*GetGdDataResp) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{21}
}

func (x *GetGdDataResp) GetList() []*AllSpInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GetJdkpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prices        []float64              `protobuf:"fixed64,1,rep,packed,name=prices,proto3" json:"prices"`
	TagList       []*JdkpTagInfo         `protobuf:"bytes,2,rep,name=tagList,proto3" json:"tagList"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJdkpResp) Reset() {
	*x = GetJdkpResp{}
	mi := &file_shares_analy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJdkpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJdkpResp) ProtoMessage() {}

func (x *GetJdkpResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJdkpResp.ProtoReflect.Descriptor instead.
func (*GetJdkpResp) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{22}
}

func (x *GetJdkpResp) GetPrices() []float64 {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *GetJdkpResp) GetTagList() []*JdkpTagInfo {
	if x != nil {
		return x.TagList
	}
	return nil
}

type JdkpInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tm            string                 `protobuf:"bytes,1,opt,name=tm,proto3" json:"tm"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price"`
	Percent       float64                `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JdkpInfo) Reset() {
	*x = JdkpInfo{}
	mi := &file_shares_analy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JdkpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JdkpInfo) ProtoMessage() {}

func (x *JdkpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JdkpInfo.ProtoReflect.Descriptor instead.
func (*JdkpInfo) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{23}
}

func (x *JdkpInfo) GetTm() string {
	if x != nil {
		return x.Tm
	}
	return ""
}

func (x *JdkpInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *JdkpInfo) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type JdkpTagInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tm            string                 `protobuf:"bytes,1,opt,name=tm,proto3" json:"tm"`
	Start         float64                `protobuf:"fixed64,2,opt,name=start,proto3" json:"start"`
	Offset        float64                `protobuf:"fixed64,3,opt,name=offset,proto3" json:"offset"`
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color"`
	Align         string                 `protobuf:"bytes,6,opt,name=align,proto3" json:"align"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JdkpTagInfo) Reset() {
	*x = JdkpTagInfo{}
	mi := &file_shares_analy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JdkpTagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JdkpTagInfo) ProtoMessage() {}

func (x *JdkpTagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_analy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JdkpTagInfo.ProtoReflect.Descriptor instead.
func (*JdkpTagInfo) Descriptor() ([]byte, []int) {
	return file_shares_analy_proto_rawDescGZIP(), []int{24}
}

func (x *JdkpTagInfo) GetTm() string {
	if x != nil {
		return x.Tm
	}
	return ""
}

func (x *JdkpTagInfo) GetStart() float64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *JdkpTagInfo) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *JdkpTagInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *JdkpTagInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *JdkpTagInfo) GetAlign() string {
	if x != nil {
		return x.Align
	}
	return ""
}

var File_shares_analy_proto protoreflect.FileDescriptor

const file_shares_analy_proto_rawDesc = "" +
	"\n" +
	"\x12shares/analy.proto\x12\x06shares\x1a\x1acommon/common_public.proto\"\x1e\n" +
	"\n" +
	"GetCjrlReq\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\"w\n" +
	"\vGetCjrlResp\x12$\n" +
	"\x04jjsj\x18\x01 \x03(\v2\x10.shares.JjrbInfoR\x04jjsj\x12 \n" +
	"\x02sj\x18\x02 \x03(\v2\x10.shares.JjrbInfoR\x02sj\x12 \n" +
	"\x02hy\x18\x03 \x03(\v2\x10.shares.JjrbInfoR\x02hy\"3\n" +
	"\vGetGjzbResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.shares.GjzbInfoR\x04list\"\x96\x01\n" +
	"\bGjzbInfo\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x01R\apercent\x12\x1c\n" +
	"\tchangeNum\x18\x03 \x01(\x01R\tchangeNum\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\")\n" +
	"\x0fGetSampleWdjReq\x12\x16\n" +
	"\x06hexinv\x18\x01 \x01(\tR\x06hexinv\"X\n" +
	"\x10GetSampleWdjResp\x12\x1a\n" +
	"\bbaseHeat\x18\x01 \x01(\x01R\bbaseHeat\x12\x18\n" +
	"\adayHeat\x18\x02 \x01(\x01R\adayHeat\x12\x0e\n" +
	"\x02rg\x18\x03 \x01(\bR\x02rg\"4\n" +
	"\fAnalyCodeReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03len\x18\x02 \x01(\x05R\x03len\":\n" +
	"\rAnalyCodeResp\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.shares.AnalyCodeInfoR\x04list\"7\n" +
	"\rAnalyCodeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04msgs\x18\x02 \x03(\tR\x04msgs\"!\n" +
	"\vGetAllSpReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"b\n" +
	"\n" +
	"SpShowInfo\x12\x0e\n" +
	"\x02d1\x18\x01 \x01(\tR\x02d1\x12\x0e\n" +
	"\x02d2\x18\x02 \x01(\tR\x02d2\x12\x0e\n" +
	"\x02d3\x18\x03 \x01(\tR\x02d3\x12\x0e\n" +
	"\x02d4\x18\x04 \x01(\tR\x02d4\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\"\x9f\x01\n" +
	"\tAllSpInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x0e\n" +
	"\x02d1\x18\x02 \x01(\tR\x02d1\x12\x0e\n" +
	"\x02d2\x18\x03 \x01(\tR\x02d2\x12\x0e\n" +
	"\x02d3\x18\x04 \x01(\tR\x02d3\x12\x0e\n" +
	"\x02d4\x18\x05 \x01(\tR\x02d4\x12\x14\n" +
	"\x05isDot\x18\x06 \x01(\bR\x05isDot\x12&\n" +
	"\x04list\x18\a \x03(\v2\x12.shares.SpShowInfoR\x04list\"\x90\x01\n" +
	"\bBaseInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x14\n" +
	"\x05name1\x18\x04 \x01(\tR\x05name1\x12\x16\n" +
	"\x06value1\x18\x05 \x01(\tR\x06value1\x12\x16\n" +
	"\x06color1\x18\x06 \x01(\tR\x06color1\"5\n" +
	"\fGetAllSpResp\x12%\n" +
	"\x04list\x18\x03 \x03(\v2\x11.shares.AllSpInfoR\x04list\"\x81\x01\n" +
	"\x0fGetBaseInfoResp\x12\x10\n" +
	"\x03vip\x18\x01 \x01(\bR\x03vip\x12\x14\n" +
	"\x05token\x18\x02 \x01(\x05R\x05token\x12,\n" +
	"\bbaseInfo\x18\x04 \x03(\v2\x10.shares.BaseInfoR\bbaseInfo\x12\x18\n" +
	"\awgjlUrl\x18\x05 \x01(\tR\awgjlUrl\"4\n" +
	"\fGetArticInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x0e\n" +
	"\x02tm\x18\x02 \x01(\tR\x02tm\"8\n" +
	"\fGetArticResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.shares.GetArticInfoR\x04list\"\xd2\x02\n" +
	"\x14GetBxNxKlineInfoResp\x12\x16\n" +
	"\x06times1\x18\n" +
	" \x03(\tR\x06times1\x12\x18\n" +
	"\adayStr1\x18\v \x01(\tR\adayStr1\x12\x10\n" +
	"\x03bs2\x18\x02 \x03(\x01R\x03bs2\x12\x10\n" +
	"\x03bs3\x18\x03 \x03(\x01R\x03bs3\x12\x10\n" +
	"\x03bs4\x18\x04 \x03(\x01R\x03bs4\x12\x10\n" +
	"\x03bs5\x18\x05 \x03(\x01R\x03bs5\x12\x10\n" +
	"\x03bs6\x18\x06 \x03(\x01R\x03bs6\x12\x10\n" +
	"\x03bs7\x18\a \x03(\x01R\x03bs7\x12\x16\n" +
	"\x06times2\x18\x14 \x03(\tR\x06times2\x12\x18\n" +
	"\adayStr2\x18\x15 \x01(\tR\adayStr2\x12\x10\n" +
	"\x03nx2\x18\x16 \x03(\x01R\x03nx2\x12\x10\n" +
	"\x03nx3\x18\x17 \x03(\x01R\x03nx3\x12\x10\n" +
	"\x03nx4\x18\x18 \x03(\x01R\x03nx4\x12\x10\n" +
	"\x03nx5\x18\x19 \x03(\x01R\x03nx5\x12\x10\n" +
	"\x03nx6\x18\x1a \x03(\x01R\x03nx6\x12\x10\n" +
	"\x03nx7\x18\x1b \x03(\x01R\x03nx7\"\xae\x01\n" +
	"\bJjrbInfo\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bprevious\x18\x03 \x01(\tR\bprevious\x12\x1c\n" +
	"\tconsensus\x18\x04 \x01(\tR\tconsensus\x12\x16\n" +
	"\x06actual\x18\x05 \x01(\tR\x06actual\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x0e\n" +
	"\x02tm\x18\a \x01(\tR\x02tm\"_\n" +
	"\tMainShare\x12\x0e\n" +
	"\x02tm\x18\x01 \x01(\tR\x02tm\x12\x14\n" +
	"\x05price\x18\x02 \x03(\x01R\x05price\x12\x12\n" +
	"\x04main\x18\x03 \x03(\x01R\x04main\x12\x18\n" +
	"\amainDay\x18\x04 \x01(\x01R\amainDay\"4\n" +
	"\fGetGdDataReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\x05R\x03tag\"6\n" +
	"\rGetGdDataResp\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.shares.AllSpInfoR\x04list\"T\n" +
	"\vGetJdkpResp\x12\x16\n" +
	"\x06prices\x18\x01 \x03(\x01R\x06prices\x12-\n" +
	"\atagList\x18\x02 \x03(\v2\x13.shares.JdkpTagInfoR\atagList\"J\n" +
	"\bJdkpInfo\x12\x0e\n" +
	"\x02tm\x18\x01 \x01(\tR\x02tm\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\"\x89\x01\n" +
	"\vJdkpTagInfo\x12\x0e\n" +
	"\x02tm\x18\x01 \x01(\tR\x02tm\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x01R\x05start\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x01R\x06offset\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12\x14\n" +
	"\x05align\x18\x06 \x01(\tR\x05align2\xe0\x03\n" +
	"\x05Analy\x12:\n" +
	"\tAnalyCode\x12\x14.shares.AnalyCodeReq\x1a\x15.shares.AnalyCodeResp\"\x00\x124\n" +
	"\x05GetSp\x12\x13.shares.GetAllSpReq\x1a\x14.shares.GetAllSpResp\"\x00\x12=\n" +
	"\vGetBaseInfo\x12\x13.shares.GetAllSpReq\x1a\x17.shares.GetBaseInfoResp\"\x00\x12C\n" +
	"\fGetSampleWdj\x12\x17.shares.GetSampleWdjReq\x1a\x18.shares.GetSampleWdjResp\"\x00\x12,\n" +
	"\aGetGjzb\x12\r.common.Empty\x1a\x10.shares.GjzbInfo\"\x00\x12A\n" +
	"\x10GetBxNxKlineInfo\x12\r.common.Empty\x1a\x1c.shares.GetBxNxKlineInfoResp\"\x00\x124\n" +
	"\aGetCjrl\x12\x12.shares.GetCjrlReq\x1a\x13.shares.GetCjrlResp\"\x00\x12:\n" +
	"\tGetGdData\x12\x14.shares.GetGdDataReq\x1a\x15.shares.GetGdDataResp\"\x00B\fZ\n" +
	"rpc/sharesb\x06proto3"

var (
	file_shares_analy_proto_rawDescOnce sync.Once
	file_shares_analy_proto_rawDescData []byte
)

func file_shares_analy_proto_rawDescGZIP() []byte {
	file_shares_analy_proto_rawDescOnce.Do(func() {
		file_shares_analy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shares_analy_proto_rawDesc), len(file_shares_analy_proto_rawDesc)))
	})
	return file_shares_analy_proto_rawDescData
}

var file_shares_analy_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_shares_analy_proto_goTypes = []any{
	(*GetCjrlReq)(nil),           // 0: shares.GetCjrlReq
	(*GetCjrlResp)(nil),          // 1: shares.GetCjrlResp
	(*GetGjzbResp)(nil),          // 2: shares.GetGjzbResp
	(*GjzbInfo)(nil),             // 3: shares.GjzbInfo
	(*GetSampleWdjReq)(nil),      // 4: shares.GetSampleWdjReq
	(*GetSampleWdjResp)(nil),     // 5: shares.GetSampleWdjResp
	(*AnalyCodeReq)(nil),         // 6: shares.AnalyCodeReq
	(*AnalyCodeResp)(nil),        // 7: shares.AnalyCodeResp
	(*AnalyCodeInfo)(nil),        // 8: shares.AnalyCodeInfo
	(*GetAllSpReq)(nil),          // 9: shares.GetAllSpReq
	(*SpShowInfo)(nil),           // 10: shares.SpShowInfo
	(*AllSpInfo)(nil),            // 11: shares.AllSpInfo
	(*BaseInfo)(nil),             // 12: shares.BaseInfo
	(*GetAllSpResp)(nil),         // 13: shares.GetAllSpResp
	(*GetBaseInfoResp)(nil),      // 14: shares.GetBaseInfoResp
	(*GetArticInfo)(nil),         // 15: shares.GetArticInfo
	(*GetArticResp)(nil),         // 16: shares.GetArticResp
	(*GetBxNxKlineInfoResp)(nil), // 17: shares.GetBxNxKlineInfoResp
	(*JjrbInfo)(nil),             // 18: shares.JjrbInfo
	(*MainShare)(nil),            // 19: shares.MainShare
	(*GetGdDataReq)(nil),         // 20: shares.GetGdDataReq
	(*GetGdDataResp)(nil),        // 21: shares.GetGdDataResp
	(*GetJdkpResp)(nil),          // 22: shares.GetJdkpResp
	(*JdkpInfo)(nil),             // 23: shares.JdkpInfo
	(*JdkpTagInfo)(nil),          // 24: shares.JdkpTagInfo
	(*common.Empty)(nil),         // 25: common.Empty
}
var file_shares_analy_proto_depIdxs = []int32{
	18, // 0: shares.GetCjrlResp.jjsj:type_name -> shares.JjrbInfo
	18, // 1: shares.GetCjrlResp.sj:type_name -> shares.JjrbInfo
	18, // 2: shares.GetCjrlResp.hy:type_name -> shares.JjrbInfo
	3,  // 3: shares.GetGjzbResp.list:type_name -> shares.GjzbInfo
	8,  // 4: shares.AnalyCodeResp.list:type_name -> shares.AnalyCodeInfo
	10, // 5: shares.AllSpInfo.list:type_name -> shares.SpShowInfo
	11, // 6: shares.GetAllSpResp.list:type_name -> shares.AllSpInfo
	12, // 7: shares.GetBaseInfoResp.baseInfo:type_name -> shares.BaseInfo
	15, // 8: shares.GetArticResp.list:type_name -> shares.GetArticInfo
	11, // 9: shares.GetGdDataResp.list:type_name -> shares.AllSpInfo
	24, // 10: shares.GetJdkpResp.tagList:type_name -> shares.JdkpTagInfo
	6,  // 11: shares.Analy.AnalyCode:input_type -> shares.AnalyCodeReq
	9,  // 12: shares.Analy.GetSp:input_type -> shares.GetAllSpReq
	9,  // 13: shares.Analy.GetBaseInfo:input_type -> shares.GetAllSpReq
	4,  // 14: shares.Analy.GetSampleWdj:input_type -> shares.GetSampleWdjReq
	25, // 15: shares.Analy.GetGjzb:input_type -> common.Empty
	25, // 16: shares.Analy.GetBxNxKlineInfo:input_type -> common.Empty
	0,  // 17: shares.Analy.GetCjrl:input_type -> shares.GetCjrlReq
	20, // 18: shares.Analy.GetGdData:input_type -> shares.GetGdDataReq
	7,  // 19: shares.Analy.AnalyCode:output_type -> shares.AnalyCodeResp
	13, // 20: shares.Analy.GetSp:output_type -> shares.GetAllSpResp
	14, // 21: shares.Analy.GetBaseInfo:output_type -> shares.GetBaseInfoResp
	5,  // 22: shares.Analy.GetSampleWdj:output_type -> shares.GetSampleWdjResp
	3,  // 23: shares.Analy.GetGjzb:output_type -> shares.GjzbInfo
	17, // 24: shares.Analy.GetBxNxKlineInfo:output_type -> shares.GetBxNxKlineInfoResp
	1,  // 25: shares.Analy.GetCjrl:output_type -> shares.GetCjrlResp
	21, // 26: shares.Analy.GetGdData:output_type -> shares.GetGdDataResp
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_shares_analy_proto_init() }
func file_shares_analy_proto_init() {
	if File_shares_analy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shares_analy_proto_rawDesc), len(file_shares_analy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shares_analy_proto_goTypes,
		DependencyIndexes: file_shares_analy_proto_depIdxs,
		MessageInfos:      file_shares_analy_proto_msgTypes,
	}.Build()
	File_shares_analy_proto = out.File
	file_shares_analy_proto_goTypes = nil
	file_shares_analy_proto_depIdxs = nil
}
