// Code generated by protoc-gen-gmsec. DO NOT EDIT.

package shares

// Tool descriptions from proto comments
const (
	// 下单
	Order_PlaceOrder_ToolDesc = "下单"
	// 计算费用
	Order_ReckonFee_ToolDesc = "计算费用"
	// 支付成功check一次
	Order_CheckPay_ToolDesc = "支付成功check一次"
)
