// Code generated by protoc-gen-gmsec. DO NOT EDIT.

package shares

// Tool descriptions from proto comments
const (
	// 获取分组信息
	Shares_GetGroup_ToolDesc = "获取分组信息"
	// 获取分组信息
	Shares_GetMyGroup_ToolDesc = "获取分组信息"
	// 更新分组信息
	Shares_UpsetGroupCode_ToolDesc = "更新分组信息"
	// 搜索
	Shares_Search_ToolDesc = "搜索"
	// 精确查找代码
	Shares_Gets_ToolDesc = "精确查找代码"
	// 获取我的监听,code不为空获取全部
	Shares_GetMyCode_ToolDesc = "获取我的监听,code不为空获取全部"
	// 获取消息
	Shares_GetMsg_ToolDesc = "获取消息"
	// 是否有新消息
	Shares_HaveNewMsg_ToolDesc = "是否有新消息"
	// 删除一个监听
	Shares_DeleteMyCode_ToolDesc = "删除一个监听"
	// 添加一个组织
	Shares_AddGroup_ToolDesc = "添加一个组织"
	// 每日复盘笔记
	Shares_GetDailyCheck_ToolDesc = "每日复盘笔记"
)
