// Code generated by protoc-gen-gmsec. DO NOT EDIT.

package shares

// Tool descriptions from proto comments
const (
	// 微信授权获取登录信息
	Weixin_Oauth_ToolDesc = "微信授权获取登录信息"
	// 获取微信二维码
	Weixin_GetQrcode_ToolDesc = "获取微信二维码"
	// 获取用户信息
	Weixin_GetUserInfo_ToolDesc = "获取用户信息"
	// 更新用户信息
	Weixin_UpsetUserInfo_ToolDesc = "更新用户信息"
	// 是否要重新登录
	Weixin_ReLogin_ToolDesc = "是否要重新登录"
)
