// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: shares/weixin.proto

package shares

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	common "rpc/common"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMagaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMagaReq) Reset() {
	*x = GetMagaReq{}
	mi := &file_shares_weixin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMagaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMagaReq) ProtoMessage() {}

func (x *GetMagaReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMagaReq.ProtoReflect.Descriptor instead.
func (*GetMagaReq) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{0}
}

func (x *GetMagaReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetMagaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maga          []*MagaInfo            `protobuf:"bytes,1,rep,name=maga,proto3" json:"maga"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMagaResp) Reset() {
	*x = GetMagaResp{}
	mi := &file_shares_weixin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMagaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMagaResp) ProtoMessage() {}

func (x *GetMagaResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMagaResp.ProtoReflect.Descriptor instead.
func (*GetMagaResp) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{1}
}

func (x *GetMagaResp) GetMaga() []*MagaInfo {
	if x != nil {
		return x.Maga
	}
	return nil
}

type MagaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MagaInfo) Reset() {
	*x = MagaInfo{}
	mi := &file_shares_weixin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MagaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagaInfo) ProtoMessage() {}

func (x *MagaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagaInfo.ProtoReflect.Descriptor instead.
func (*MagaInfo) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{2}
}

func (x *MagaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MagaInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MagaInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type H5LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *H5LoginReq) Reset() {
	*x = H5LoginReq{}
	mi := &file_shares_weixin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *H5LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H5LoginReq) ProtoMessage() {}

func (x *H5LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H5LoginReq.ProtoReflect.Descriptor instead.
func (*H5LoginReq) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{3}
}

func (x *H5LoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type H5LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status"`      // 状态，0：正在登录中，1：登录成功，
	UserId        string                 `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId"`       // 用户id
	UserName      string                 `protobuf:"bytes,5,opt,name=userName,proto3" json:"userName"`   // 用户名
	AvatarUrl     string                 `protobuf:"bytes,6,opt,name=avatarUrl,proto3" json:"avatarUrl"` // 头像地址
	Rg            bool                   `protobuf:"varint,7,opt,name=rg,proto3" json:"rg"`              // 是否涨绿跌红
	Vip           bool                   `protobuf:"varint,8,opt,name=vip,proto3" json:"vip"`            // 是否是vip
	SessionId     string                 `protobuf:"bytes,9,opt,name=sessionId,proto3" json:"sessionId"` // 用户sessionid 用于当前交互使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *H5LoginResp) Reset() {
	*x = H5LoginResp{}
	mi := &file_shares_weixin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *H5LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H5LoginResp) ProtoMessage() {}

func (x *H5LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H5LoginResp.ProtoReflect.Descriptor instead.
func (*H5LoginResp) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{4}
}

func (x *H5LoginResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *H5LoginResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *H5LoginResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *H5LoginResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *H5LoginResp) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *H5LoginResp) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *H5LoginResp) GetRg() bool {
	if x != nil {
		return x.Rg
	}
	return false
}

func (x *H5LoginResp) GetVip() bool {
	if x != nil {
		return x.Vip
	}
	return false
}

func (x *H5LoginResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetJsSignReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJsSignReq) Reset() {
	*x = GetJsSignReq{}
	mi := &file_shares_weixin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJsSignReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJsSignReq) ProtoMessage() {}

func (x *GetJsSignReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJsSignReq.ProtoReflect.Descriptor instead.
func (*GetJsSignReq) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{5}
}

func (x *GetJsSignReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetJsSignResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         string                 `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid"`
	Noncestr      string                 `protobuf:"bytes,2,opt,name=noncestr,proto3" json:"noncestr"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJsSignResp) Reset() {
	*x = GetJsSignResp{}
	mi := &file_shares_weixin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJsSignResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJsSignResp) ProtoMessage() {}

func (x *GetJsSignResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJsSignResp.ProtoReflect.Descriptor instead.
func (*GetJsSignResp) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{6}
}

func (x *GetJsSignResp) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *GetJsSignResp) GetNoncestr() string {
	if x != nil {
		return x.Noncestr
	}
	return ""
}

func (x *GetJsSignResp) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *GetJsSignResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetJsSignResp) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// OauthReq 请求结构
type OauthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jscode        string                 `protobuf:"bytes,1,opt,name=jscode,proto3" json:"jscode"`              // 微信端jscode
	IsUpdateUser  bool                   `protobuf:"varint,2,opt,name=isUpdateUser,proto3" json:"isUpdateUser"` // 是否更新用户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthReq) Reset() {
	*x = OauthReq{}
	mi := &file_shares_weixin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthReq) ProtoMessage() {}

func (x *OauthReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthReq.ProtoReflect.Descriptor instead.
func (*OauthReq) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{7}
}

func (x *OauthReq) GetJscode() string {
	if x != nil {
		return x.Jscode
	}
	return ""
}

func (x *OauthReq) GetIsUpdateUser() bool {
	if x != nil {
		return x.IsUpdateUser
	}
	return false
}

// OauthResp 微信授权返回信息
type OauthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId"`      // 用户sessionid 用于当前交互使用
	OpenId        string                 `protobuf:"bytes,2,opt,name=openId,proto3" json:"openId"`            // openid
	OverdueTime   int64                  `protobuf:"varint,3,opt,name=overdueTime,proto3" json:"overdueTime"` // 逾期时间点(时间戳)
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level"`             // 等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthResp) Reset() {
	*x = OauthResp{}
	mi := &file_shares_weixin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthResp) ProtoMessage() {}

func (x *OauthResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthResp.ProtoReflect.Descriptor instead.
func (*OauthResp) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{8}
}

func (x *OauthResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OauthResp) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *OauthResp) GetOverdueTime() int64 {
	if x != nil {
		return x.OverdueTime
	}
	return 0
}

func (x *OauthResp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// WxUserinfo 用户信息
type WxUserinfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID"` // 用户sessionid 用于当前交互使用
	NickName      string                 `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName"`   //用户昵称
	AvatarURL     string                 `protobuf:"bytes,3,opt,name=avatarURL,proto3" json:"avatarURL"` //用户头像，最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender"`       //用户的性别，值为1时是男性，值为2时是女性，值为0时是未知
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city"`           //用户所在城市
	Province      string                 `protobuf:"bytes,6,opt,name=province,proto3" json:"province"`   //用户所在省份
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country"`     //用户所在国家
	Language      string                 `protobuf:"bytes,8,opt,name=language,proto3" json:"language"`   //用户的语言，简体中文为zh_CN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxUserinfo) Reset() {
	*x = WxUserinfo{}
	mi := &file_shares_weixin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxUserinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxUserinfo) ProtoMessage() {}

func (x *WxUserinfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxUserinfo.ProtoReflect.Descriptor instead.
func (*WxUserinfo) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{9}
}

func (x *WxUserinfo) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *WxUserinfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *WxUserinfo) GetAvatarURL() string {
	if x != nil {
		return x.AvatarURL
	}
	return ""
}

func (x *WxUserinfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *WxUserinfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *WxUserinfo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *WxUserinfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *WxUserinfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// WxUserinfoResp 用户信息返回
type WxUserinfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             bool                   `protobuf:"varint,1,opt,name=b,proto3" json:"b"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxUserinfoResp) Reset() {
	*x = WxUserinfoResp{}
	mi := &file_shares_weixin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxUserinfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxUserinfoResp) ProtoMessage() {}

func (x *WxUserinfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxUserinfoResp.ProtoReflect.Descriptor instead.
func (*WxUserinfoResp) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{10}
}

func (x *WxUserinfoResp) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

// GetQrcodeResp 获取二维码
type GetQrcodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          string                 `protobuf:"bytes,1,opt,name=page,proto3" json:"page"`   // 小程序页面头部
	Scene         string                 `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene"` // 附带参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQrcodeReq) Reset() {
	*x = GetQrcodeReq{}
	mi := &file_shares_weixin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQrcodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQrcodeReq) ProtoMessage() {}

func (x *GetQrcodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQrcodeReq.ProtoReflect.Descriptor instead.
func (*GetQrcodeReq) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{11}
}

func (x *GetQrcodeReq) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *GetQrcodeReq) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

// GetQrcodeResp 获取二维码
type GetQrcodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url"` // 二维码图片地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQrcodeResp) Reset() {
	*x = GetQrcodeResp{}
	mi := &file_shares_weixin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQrcodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQrcodeResp) ProtoMessage() {}

func (x *GetQrcodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQrcodeResp.ProtoReflect.Descriptor instead.
func (*GetQrcodeResp) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{12}
}

func (x *GetQrcodeResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// GetUserInfoReq 用户信息
type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hexinv        string                 `protobuf:"bytes,1,opt,name=hexinv,proto3" json:"hexinv"` // 核心
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_shares_weixin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserInfoReq) GetHexinv() string {
	if x != nil {
		return x.Hexinv
	}
	return ""
}

// GetUserInfoResp 用户信息
type GetUserInfoResp struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Openid      string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid"`             // 用户openid
	NickName    string                 `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName"`         // 用户昵称
	AvatarURL   string                 `protobuf:"bytes,3,opt,name=avatarURL,proto3" json:"avatarURL"`       // 用户头像地址
	Gender      string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender"`             // 用户的性别
	City        string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city"`                 // 用户所在城市
	Province    string                 `protobuf:"bytes,6,opt,name=province,proto3" json:"province"`         // 用户所在省份
	Country     string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country"`           // 用户所在国家
	Phone       string                 `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone"`               // 用户手机号
	Group       string                 `protobuf:"bytes,9,opt,name=group,proto3" json:"group"`               // 用户所在分组列表
	Token       int32                  `protobuf:"varint,10,opt,name=token,proto3" json:"token"`             // 可用容量
	VipOutTime  string                 `protobuf:"bytes,11,opt,name=vipOutTime,proto3" json:"vipOutTime"`    // 会员过期时间
	VipLevel    int32                  `protobuf:"varint,12,opt,name=vipLevel,proto3" json:"vipLevel"`       // vip等级
	IsVip       bool                   `protobuf:"varint,13,opt,name=isVip,proto3" json:"isVip"`             // 是否是vip
	Rg          bool                   `protobuf:"varint,14,opt,name=rg,proto3" json:"rg"`                   // 是否涨绿跌红
	CacheTime   int64                  `protobuf:"varint,15,opt,name=cacheTime,proto3" json:"cacheTime"`     // 缓存时间
	Msg         string                 `protobuf:"bytes,16,opt,name=msg,proto3" json:"msg"`                  // 消息,每日签到等消息
	SessionId   string                 `protobuf:"bytes,17,opt,name=sessionId,proto3" json:"sessionId"`      // 用户sessionid 用于当前交互使用
	OverdueTime int64                  `protobuf:"varint,18,opt,name=overdueTime,proto3" json:"overdueTime"` // 逾期时间点(时间戳)
	// bool relogin = 19;// 是否重新登录:true 重新登录
	KvList        []*UserKvInfo `protobuf:"bytes,26,rep,name=kvList,proto3" json:"kvList"` // 用户自定义信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResp) Reset() {
	*x = GetUserInfoResp{}
	mi := &file_shares_weixin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResp) ProtoMessage() {}

func (x *GetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserInfoResp) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *GetUserInfoResp) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *GetUserInfoResp) GetAvatarURL() string {
	if x != nil {
		return x.AvatarURL
	}
	return ""
}

func (x *GetUserInfoResp) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *GetUserInfoResp) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetUserInfoResp) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GetUserInfoResp) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetUserInfoResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserInfoResp) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetUserInfoResp) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *GetUserInfoResp) GetVipOutTime() string {
	if x != nil {
		return x.VipOutTime
	}
	return ""
}

func (x *GetUserInfoResp) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

func (x *GetUserInfoResp) GetIsVip() bool {
	if x != nil {
		return x.IsVip
	}
	return false
}

func (x *GetUserInfoResp) GetRg() bool {
	if x != nil {
		return x.Rg
	}
	return false
}

func (x *GetUserInfoResp) GetCacheTime() int64 {
	if x != nil {
		return x.CacheTime
	}
	return 0
}

func (x *GetUserInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserInfoResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetUserInfoResp) GetOverdueTime() int64 {
	if x != nil {
		return x.OverdueTime
	}
	return 0
}

func (x *GetUserInfoResp) GetKvList() []*UserKvInfo {
	if x != nil {
		return x.KvList
	}
	return nil
}

type UserKvInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Value         bool                   `protobuf:"varint,3,opt,name=value,proto3" json:"value"`
	ActiveColor   string                 `protobuf:"bytes,4,opt,name=activeColor,proto3" json:"activeColor"`     // 激活颜色
	InactiveColor string                 `protobuf:"bytes,5,opt,name=inactiveColor,proto3" json:"inactiveColor"` // 未激活颜色
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserKvInfo) Reset() {
	*x = UserKvInfo{}
	mi := &file_shares_weixin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserKvInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKvInfo) ProtoMessage() {}

func (x *UserKvInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKvInfo.ProtoReflect.Descriptor instead.
func (*UserKvInfo) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{15}
}

func (x *UserKvInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UserKvInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserKvInfo) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *UserKvInfo) GetActiveColor() string {
	if x != nil {
		return x.ActiveColor
	}
	return ""
}

func (x *UserKvInfo) GetInactiveColor() string {
	if x != nil {
		return x.InactiveColor
	}
	return ""
}

type UpsetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsetUserInfoReq) Reset() {
	*x = UpsetUserInfoReq{}
	mi := &file_shares_weixin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsetUserInfoReq) ProtoMessage() {}

func (x *UpsetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsetUserInfoReq.ProtoReflect.Descriptor instead.
func (*UpsetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{16}
}

func (x *UpsetUserInfoReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpsetUserInfoReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ReLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relogin       bool                   `protobuf:"varint,1,opt,name=relogin,proto3" json:"relogin"`         // 是否重新登录:true 重新登录
	SessionId     string                 `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId"`      // 用户sessionid 用于当前交互使用
	OpenId        string                 `protobuf:"bytes,3,opt,name=openId,proto3" json:"openId"`            // openid
	OverdueTime   int64                  `protobuf:"varint,4,opt,name=overdueTime,proto3" json:"overdueTime"` // 逾期时间点(时间戳)
	Msg           string                 `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg"`                  // 消息
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level"`             // 等级
	NickName      string                 `protobuf:"bytes,7,opt,name=nickName,proto3" json:"nickName"`        // 用户昵称
	AvatarURL     string                 `protobuf:"bytes,8,opt,name=avatarURL,proto3" json:"avatarURL"`      // 用户头像地址
	Rg            bool                   `protobuf:"varint,9,opt,name=rg,proto3" json:"rg"`                   // 是否涨绿跌红
	Vip           bool                   `protobuf:"varint,10,opt,name=vip,proto3" json:"vip"`                // 是否是vip
	VipOutTime    string                 `protobuf:"bytes,11,opt,name=vipOutTime,proto3" json:"vipOutTime"`   // 会员过期时间
	VipLevel      int32                  `protobuf:"varint,12,opt,name=vipLevel,proto3" json:"vipLevel"`      // vip等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReLoginResp) Reset() {
	*x = ReLoginResp{}
	mi := &file_shares_weixin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReLoginResp) ProtoMessage() {}

func (x *ReLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReLoginResp.ProtoReflect.Descriptor instead.
func (*ReLoginResp) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{17}
}

func (x *ReLoginResp) GetRelogin() bool {
	if x != nil {
		return x.Relogin
	}
	return false
}

func (x *ReLoginResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReLoginResp) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *ReLoginResp) GetOverdueTime() int64 {
	if x != nil {
		return x.OverdueTime
	}
	return 0
}

func (x *ReLoginResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReLoginResp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ReLoginResp) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *ReLoginResp) GetAvatarURL() string {
	if x != nil {
		return x.AvatarURL
	}
	return ""
}

func (x *ReLoginResp) GetRg() bool {
	if x != nil {
		return x.Rg
	}
	return false
}

func (x *ReLoginResp) GetVip() bool {
	if x != nil {
		return x.Vip
	}
	return false
}

func (x *ReLoginResp) GetVipOutTime() string {
	if x != nil {
		return x.VipOutTime
	}
	return ""
}

func (x *ReLoginResp) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

type CheckVersionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version"`   // 版本号
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform"` // 平台
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckVersionReq) Reset() {
	*x = CheckVersionReq{}
	mi := &file_shares_weixin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVersionReq) ProtoMessage() {}

func (x *CheckVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVersionReq.ProtoReflect.Descriptor instead.
func (*CheckVersionReq) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{18}
}

func (x *CheckVersionReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CheckVersionReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type CheckVersionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version"`   // 版本号
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform"` // 平台
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url"`           // 地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckVersionResp) Reset() {
	*x = CheckVersionResp{}
	mi := &file_shares_weixin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVersionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVersionResp) ProtoMessage() {}

func (x *CheckVersionResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVersionResp.ProtoReflect.Descriptor instead.
func (*CheckVersionResp) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{19}
}

func (x *CheckVersionResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CheckVersionResp) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CheckVersionResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetKlineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`   // 股票代码
	Kline         []string               `protobuf:"bytes,2,rep,name=kline,proto3" json:"kline"` // K线数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKlineResp) Reset() {
	*x = GetKlineResp{}
	mi := &file_shares_weixin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKlineResp) ProtoMessage() {}

func (x *GetKlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKlineResp.ProtoReflect.Descriptor instead.
func (*GetKlineResp) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{20}
}

func (x *GetKlineResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetKlineResp) GetKline() []string {
	if x != nil {
		return x.Kline
	}
	return nil
}

type GetVersionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           string                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac"`         // 版本号
	Windows       string                 `protobuf:"bytes,2,opt,name=windows,proto3" json:"windows"` // 平台
	Vscode        string                 `protobuf:"bytes,3,opt,name=vscode,proto3" json:"vscode"`   // 地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResp) Reset() {
	*x = GetVersionResp{}
	mi := &file_shares_weixin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResp) ProtoMessage() {}

func (x *GetVersionResp) ProtoReflect() protoreflect.Message {
	mi := &file_shares_weixin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResp.ProtoReflect.Descriptor instead.
func (*GetVersionResp) Descriptor() ([]byte, []int) {
	return file_shares_weixin_proto_rawDescGZIP(), []int{21}
}

func (x *GetVersionResp) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *GetVersionResp) GetWindows() string {
	if x != nil {
		return x.Windows
	}
	return ""
}

func (x *GetVersionResp) GetVscode() string {
	if x != nil {
		return x.Vscode
	}
	return ""
}

var File_shares_weixin_proto protoreflect.FileDescriptor

const file_shares_weixin_proto_rawDesc = "" +
	"\n" +
	"\x13shares/weixin.proto\x12\x06shares\x1a\x1acommon/common_public.proto\" \n" +
	"\n" +
	"GetMagaReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"3\n" +
	"\vGetMagaResp\x12$\n" +
	"\x04maga\x18\x01 \x03(\v2\x10.shares.MagaInfoR\x04maga\"D\n" +
	"\bMagaInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\" \n" +
	"\n" +
	"H5LoginReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xdd\x01\n" +
	"\vH5LoginResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\tR\x06userId\x12\x1a\n" +
	"\buserName\x18\x05 \x01(\tR\buserName\x12\x1c\n" +
	"\tavatarUrl\x18\x06 \x01(\tR\tavatarUrl\x12\x0e\n" +
	"\x02rg\x18\a \x01(\bR\x02rg\x12\x10\n" +
	"\x03vip\x18\b \x01(\bR\x03vip\x12\x1c\n" +
	"\tsessionId\x18\t \x01(\tR\tsessionId\" \n" +
	"\fGetJsSignReq\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x8f\x01\n" +
	"\rGetJsSignResp\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\tR\x05appid\x12\x1a\n" +
	"\bnoncestr\x18\x02 \x01(\tR\bnoncestr\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\"F\n" +
	"\bOauthReq\x12\x16\n" +
	"\x06jscode\x18\x01 \x01(\tR\x06jscode\x12\"\n" +
	"\fisUpdateUser\x18\x02 \x01(\bR\fisUpdateUser\"y\n" +
	"\tOauthResp\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06openId\x18\x02 \x01(\tR\x06openId\x12 \n" +
	"\voverdueTime\x18\x03 \x01(\x03R\voverdueTime\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\"\xe2\x01\n" +
	"\n" +
	"WxUserinfo\x12\x1c\n" +
	"\tsessionID\x18\x01 \x01(\tR\tsessionID\x12\x1a\n" +
	"\bnickName\x18\x02 \x01(\tR\bnickName\x12\x1c\n" +
	"\tavatarURL\x18\x03 \x01(\tR\tavatarURL\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1a\n" +
	"\bprovince\x18\x06 \x01(\tR\bprovince\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\"\x1e\n" +
	"\x0eWxUserinfoResp\x12\f\n" +
	"\x01b\x18\x01 \x01(\bR\x01b\"8\n" +
	"\fGetQrcodeReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\tR\x04page\x12\x14\n" +
	"\x05scene\x18\x02 \x01(\tR\x05scene\"!\n" +
	"\rGetQrcodeResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"(\n" +
	"\x0eGetUserInfoReq\x12\x16\n" +
	"\x06hexinv\x18\x01 \x01(\tR\x06hexinv\"\x85\x04\n" +
	"\x0fGetUserInfoResp\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\x12\x1a\n" +
	"\bnickName\x18\x02 \x01(\tR\bnickName\x12\x1c\n" +
	"\tavatarURL\x18\x03 \x01(\tR\tavatarURL\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1a\n" +
	"\bprovince\x18\x06 \x01(\tR\bprovince\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12\x14\n" +
	"\x05group\x18\t \x01(\tR\x05group\x12\x14\n" +
	"\x05token\x18\n" +
	" \x01(\x05R\x05token\x12\x1e\n" +
	"\n" +
	"vipOutTime\x18\v \x01(\tR\n" +
	"vipOutTime\x12\x1a\n" +
	"\bvipLevel\x18\f \x01(\x05R\bvipLevel\x12\x14\n" +
	"\x05isVip\x18\r \x01(\bR\x05isVip\x12\x0e\n" +
	"\x02rg\x18\x0e \x01(\bR\x02rg\x12\x1c\n" +
	"\tcacheTime\x18\x0f \x01(\x03R\tcacheTime\x12\x10\n" +
	"\x03msg\x18\x10 \x01(\tR\x03msg\x12\x1c\n" +
	"\tsessionId\x18\x11 \x01(\tR\tsessionId\x12 \n" +
	"\voverdueTime\x18\x12 \x01(\x03R\voverdueTime\x12*\n" +
	"\x06kvList\x18\x1a \x03(\v2\x12.shares.UserKvInfoR\x06kvList\"\x90\x01\n" +
	"\n" +
	"UserKvInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\bR\x05value\x12 \n" +
	"\vactiveColor\x18\x04 \x01(\tR\vactiveColor\x12$\n" +
	"\rinactiveColor\x18\x05 \x01(\tR\rinactiveColor\":\n" +
	"\x10UpsetUserInfoReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xbf\x02\n" +
	"\vReLoginResp\x12\x18\n" +
	"\arelogin\x18\x01 \x01(\bR\arelogin\x12\x1c\n" +
	"\tsessionId\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06openId\x18\x03 \x01(\tR\x06openId\x12 \n" +
	"\voverdueTime\x18\x04 \x01(\x03R\voverdueTime\x12\x10\n" +
	"\x03msg\x18\x05 \x01(\tR\x03msg\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x1a\n" +
	"\bnickName\x18\a \x01(\tR\bnickName\x12\x1c\n" +
	"\tavatarURL\x18\b \x01(\tR\tavatarURL\x12\x0e\n" +
	"\x02rg\x18\t \x01(\bR\x02rg\x12\x10\n" +
	"\x03vip\x18\n" +
	" \x01(\bR\x03vip\x12\x1e\n" +
	"\n" +
	"vipOutTime\x18\v \x01(\tR\n" +
	"vipOutTime\x12\x1a\n" +
	"\bvipLevel\x18\f \x01(\x05R\bvipLevel\"G\n" +
	"\x0fCheckVersionReq\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"Z\n" +
	"\x10CheckVersionResp\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"8\n" +
	"\fGetKlineResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05kline\x18\x02 \x03(\tR\x05kline\"T\n" +
	"\x0eGetVersionResp\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12\x18\n" +
	"\awindows\x18\x02 \x01(\tR\awindows\x12\x16\n" +
	"\x06vscode\x18\x03 \x01(\tR\x06vscode2\x96\x04\n" +
	"\x06Weixin\x12.\n" +
	"\x05Oauth\x12\x10.shares.OauthReq\x1a\x11.shares.OauthResp\"\x00\x12:\n" +
	"\tGetQrcode\x12\x14.shares.GetQrcodeReq\x1a\x15.shares.GetQrcodeResp\"\x00\x12@\n" +
	"\vGetUserInfo\x12\x16.shares.GetUserInfoReq\x1a\x17.shares.GetUserInfoResp\"\x00\x12:\n" +
	"\rUpsetUserInfo\x12\x18.shares.UpsetUserInfoReq\x1a\r.common.Empty\"\x00\x128\n" +
	"\aReLogin\x12\x16.shares.GetUserInfoReq\x1a\x13.shares.ReLoginResp\"\x00\x12:\n" +
	"\tGetJsSign\x12\x14.shares.GetJsSignReq\x1a\x15.shares.GetJsSignResp\"\x00\x121\n" +
	"\n" +
	"ClearLogin\x12\x12.shares.H5LoginReq\x1a\r.common.Empty\"\x00\x124\n" +
	"\aGetMaga\x12\x12.shares.GetMagaReq\x1a\x13.shares.GetMagaResp\"\x00\x12C\n" +
	"\fCheckVersion\x12\x17.shares.CheckVersionReq\x1a\x18.shares.CheckVersionResp\"\x00B\fZ\n" +
	"rpc/sharesb\x06proto3"

var (
	file_shares_weixin_proto_rawDescOnce sync.Once
	file_shares_weixin_proto_rawDescData []byte
)

func file_shares_weixin_proto_rawDescGZIP() []byte {
	file_shares_weixin_proto_rawDescOnce.Do(func() {
		file_shares_weixin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shares_weixin_proto_rawDesc), len(file_shares_weixin_proto_rawDesc)))
	})
	return file_shares_weixin_proto_rawDescData
}

var file_shares_weixin_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_shares_weixin_proto_goTypes = []any{
	(*GetMagaReq)(nil),       // 0: shares.GetMagaReq
	(*GetMagaResp)(nil),      // 1: shares.GetMagaResp
	(*MagaInfo)(nil),         // 2: shares.MagaInfo
	(*H5LoginReq)(nil),       // 3: shares.H5LoginReq
	(*H5LoginResp)(nil),      // 4: shares.H5LoginResp
	(*GetJsSignReq)(nil),     // 5: shares.GetJsSignReq
	(*GetJsSignResp)(nil),    // 6: shares.GetJsSignResp
	(*OauthReq)(nil),         // 7: shares.OauthReq
	(*OauthResp)(nil),        // 8: shares.OauthResp
	(*WxUserinfo)(nil),       // 9: shares.WxUserinfo
	(*WxUserinfoResp)(nil),   // 10: shares.WxUserinfoResp
	(*GetQrcodeReq)(nil),     // 11: shares.GetQrcodeReq
	(*GetQrcodeResp)(nil),    // 12: shares.GetQrcodeResp
	(*GetUserInfoReq)(nil),   // 13: shares.GetUserInfoReq
	(*GetUserInfoResp)(nil),  // 14: shares.GetUserInfoResp
	(*UserKvInfo)(nil),       // 15: shares.UserKvInfo
	(*UpsetUserInfoReq)(nil), // 16: shares.UpsetUserInfoReq
	(*ReLoginResp)(nil),      // 17: shares.ReLoginResp
	(*CheckVersionReq)(nil),  // 18: shares.CheckVersionReq
	(*CheckVersionResp)(nil), // 19: shares.CheckVersionResp
	(*GetKlineResp)(nil),     // 20: shares.GetKlineResp
	(*GetVersionResp)(nil),   // 21: shares.GetVersionResp
	(*common.Empty)(nil),     // 22: common.Empty
}
var file_shares_weixin_proto_depIdxs = []int32{
	2,  // 0: shares.GetMagaResp.maga:type_name -> shares.MagaInfo
	15, // 1: shares.GetUserInfoResp.kvList:type_name -> shares.UserKvInfo
	7,  // 2: shares.Weixin.Oauth:input_type -> shares.OauthReq
	11, // 3: shares.Weixin.GetQrcode:input_type -> shares.GetQrcodeReq
	13, // 4: shares.Weixin.GetUserInfo:input_type -> shares.GetUserInfoReq
	16, // 5: shares.Weixin.UpsetUserInfo:input_type -> shares.UpsetUserInfoReq
	13, // 6: shares.Weixin.ReLogin:input_type -> shares.GetUserInfoReq
	5,  // 7: shares.Weixin.GetJsSign:input_type -> shares.GetJsSignReq
	3,  // 8: shares.Weixin.ClearLogin:input_type -> shares.H5LoginReq
	0,  // 9: shares.Weixin.GetMaga:input_type -> shares.GetMagaReq
	18, // 10: shares.Weixin.CheckVersion:input_type -> shares.CheckVersionReq
	8,  // 11: shares.Weixin.Oauth:output_type -> shares.OauthResp
	12, // 12: shares.Weixin.GetQrcode:output_type -> shares.GetQrcodeResp
	14, // 13: shares.Weixin.GetUserInfo:output_type -> shares.GetUserInfoResp
	22, // 14: shares.Weixin.UpsetUserInfo:output_type -> common.Empty
	17, // 15: shares.Weixin.ReLogin:output_type -> shares.ReLoginResp
	6,  // 16: shares.Weixin.GetJsSign:output_type -> shares.GetJsSignResp
	22, // 17: shares.Weixin.ClearLogin:output_type -> common.Empty
	1,  // 18: shares.Weixin.GetMaga:output_type -> shares.GetMagaResp
	19, // 19: shares.Weixin.CheckVersion:output_type -> shares.CheckVersionResp
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_shares_weixin_proto_init() }
func file_shares_weixin_proto_init() {
	if File_shares_weixin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shares_weixin_proto_rawDesc), len(file_shares_weixin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shares_weixin_proto_goTypes,
		DependencyIndexes: file_shares_weixin_proto_depIdxs,
		MessageInfos:      file_shares_weixin_proto_msgTypes,
	}.Build()
	File_shares_weixin_proto = out.File
	file_shares_weixin_proto_goTypes = nil
	file_shares_weixin_proto_depIdxs = nil
}
