// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: ccmy/ccmy.proto

package ccmy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	common "rpc/common"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenId string `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId"`
	Tag    int32  `protobuf:"varint,2,opt,name=tag,proto3" json:"tag"` // 标记(0:申请，1:同意，-1：不同意)
}

func (x *RequestReq) Reset() {
	*x = RequestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReq) ProtoMessage() {}

func (x *RequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReq.ProtoReflect.Descriptor instead.
func (*RequestReq) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{0}
}

func (x *RequestReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *RequestReq) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

type GetAllRequestResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*UInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list"` // 门店
}

func (x *GetAllRequestResp) Reset() {
	*x = GetAllRequestResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequestResp) ProtoMessage() {}

func (x *GetAllRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequestResp.ProtoReflect.Descriptor instead.
func (*GetAllRequestResp) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllRequestResp) GetList() []*UInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type UInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpenId string `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Url    string `protobuf:"bytes,3,opt,name=url,proto3" json:"url"` // 照片
}

func (x *UInfo) Reset() {
	*x = UInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInfo) ProtoMessage() {}

func (x *UInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInfo.ProtoReflect.Descriptor instead.
func (*UInfo) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{2}
}

func (x *UInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *UInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateUserGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store  []string `protobuf:"bytes,1,rep,name=store,proto3" json:"store"`   // 门店
	Openid string   `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid"` //
}

func (x *UpdateUserGroupReq) Reset() {
	*x = UpdateUserGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserGroupReq) ProtoMessage() {}

func (x *UpdateUserGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserGroupReq.ProtoReflect.Descriptor instead.
func (*UpdateUserGroupReq) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserGroupReq) GetStore() []string {
	if x != nil {
		return x.Store
	}
	return nil
}

func (x *UpdateUserGroupReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

type AddGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store string `protobuf:"bytes,1,opt,name=store,proto3" json:"store"` // 门店
}

func (x *AddGroupReq) Reset() {
	*x = AddGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupReq) ProtoMessage() {}

func (x *AddGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupReq.ProtoReflect.Descriptor instead.
func (*AddGroupReq) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{4}
}

func (x *AddGroupReq) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

type AddDocReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store string `protobuf:"bytes,1,opt,name=store,proto3" json:"store"` // 门店
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`   // 姓名
	Url   string `protobuf:"bytes,3,opt,name=url,proto3" json:"url"`     // 照片
	Doc   string `protobuf:"bytes,4,opt,name=doc,proto3" json:"doc"`     // 描述
	Type  string `protobuf:"bytes,5,opt,name=type,proto3" json:"type"`   // 追加头
}

func (x *AddDocReq) Reset() {
	*x = AddDocReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDocReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocReq) ProtoMessage() {}

func (x *AddDocReq) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocReq.ProtoReflect.Descriptor instead.
func (*AddDocReq) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{5}
}

func (x *AddDocReq) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *AddDocReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddDocReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddDocReq) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *AddDocReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetStoreResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list"` // 门店列表
}

func (x *GetStoreResp) Reset() {
	*x = GetStoreResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreResp) ProtoMessage() {}

func (x *GetStoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreResp.ProtoReflect.Descriptor instead.
func (*GetStoreResp) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{6}
}

func (x *GetStoreResp) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type AddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store string `protobuf:"bytes,1,opt,name=store,proto3" json:"store"` // 门店
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`   // 姓名
	Url   string `protobuf:"bytes,3,opt,name=url,proto3" json:"url"`     // 照片
	Doc   string `protobuf:"bytes,4,opt,name=doc,proto3" json:"doc"`     // 描述
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{7}
}

func (x *AddReq) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *AddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddReq) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

type NameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store"` // 门店
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names"` //名字
}

func (x *NameResp) Reset() {
	*x = NameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResp) ProtoMessage() {}

func (x *NameResp) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResp.ProtoReflect.Descriptor instead.
func (*NameResp) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{8}
}

func (x *NameResp) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *NameResp) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type GetAllNameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameResp []*NameResp `protobuf:"bytes,1,rep,name=nameResp,proto3" json:"nameResp"` // 名字
}

func (x *GetAllNameResp) Reset() {
	*x = GetAllNameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNameResp) ProtoMessage() {}

func (x *GetAllNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNameResp.ProtoReflect.Descriptor instead.
func (*GetAllNameResp) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllNameResp) GetNameResp() []*NameResp {
	if x != nil {
		return x.NameResp
	}
	return nil
}

type SearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store string `protobuf:"bytes,1,opt,name=store,proto3" json:"store"` // 门店
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`   // 姓名
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{10}
}

func (x *SearchReq) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *SearchReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DocInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tm  string `protobuf:"bytes,1,opt,name=tm,proto3" json:"tm"`   // 时间
	Doc string `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc"` // 描述
}

func (x *DocInfo) Reset() {
	*x = DocInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocInfo) ProtoMessage() {}

func (x *DocInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocInfo.ProtoReflect.Descriptor instead.
func (*DocInfo) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{11}
}

func (x *DocInfo) GetTm() string {
	if x != nil {
		return x.Tm
	}
	return ""
}

func (x *DocInfo) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

type SearchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store string     `protobuf:"bytes,1,opt,name=store,proto3" json:"store"` // 门店
	Name  string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`   // 姓名
	Url   string     `protobuf:"bytes,3,opt,name=url,proto3" json:"url"`     // 照片
	Docs  []*DocInfo `protobuf:"bytes,4,rep,name=docs,proto3" json:"docs"`   // 描述
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccmy_ccmy_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_ccmy_ccmy_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_ccmy_ccmy_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResp) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *SearchResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SearchResp) GetDocs() []*DocInfo {
	if x != nil {
		return x.Docs
	}
	return nil
}

var File_ccmy_ccmy_proto protoreflect.FileDescriptor

var file_ccmy_ccmy_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x63, 0x6d, 0x79, 0x2f, 0x63, 0x63, 0x6d, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x63, 0x63, 0x6d, 0x79, 0x1a, 0x1a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x34, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x63, 0x63, 0x6d, 0x79, 0x2e, 0x55, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x22, 0x45, 0x0a, 0x05, 0x55, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70,
	0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x42, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x0b,
	0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x22, 0x6d, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x44, 0x6f, 0x63, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6f, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x22, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6f, 0x63, 0x22, 0x36, 0x0a, 0x08,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x08, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x63, 0x6d, 0x79, 0x2e,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x35, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x07, 0x44, 0x6f, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x74, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x64, 0x6f, 0x63, 0x22, 0x6b, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x12, 0x21, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x63, 0x63, 0x6d, 0x79, 0x2e, 0x44, 0x6f, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64,
	0x6f, 0x63, 0x73, 0x32, 0xc4, 0x03, 0x0a, 0x04, 0x63, 0x63, 0x6d, 0x79, 0x12, 0x2f, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x63, 0x63, 0x6d, 0x79, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x24, 0x0a,
	0x03, 0x41, 0x64, 0x64, 0x12, 0x0c, 0x2e, 0x63, 0x63, 0x6d, 0x79, 0x2e, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x44, 0x6f, 0x63, 0x12, 0x0f, 0x2e,
	0x63, 0x63, 0x6d, 0x79, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x6f, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x0d,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x33, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0d, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x63,
	0x63, 0x6d, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0f,
	0x2e, 0x63, 0x63, 0x6d, 0x79, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x63, 0x63, 0x6d, 0x79, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x11, 0x2e, 0x63, 0x63, 0x6d, 0x79, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x2e, 0x63, 0x63, 0x6d, 0x79, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x1a, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x39, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x17, 0x2e, 0x63, 0x63, 0x6d, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x63, 0x63, 0x6d, 0x79, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x72, 0x70,
	0x63, 0x2f, 0x63, 0x63, 0x6d, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ccmy_ccmy_proto_rawDescOnce sync.Once
	file_ccmy_ccmy_proto_rawDescData = file_ccmy_ccmy_proto_rawDesc
)

func file_ccmy_ccmy_proto_rawDescGZIP() []byte {
	file_ccmy_ccmy_proto_rawDescOnce.Do(func() {
		file_ccmy_ccmy_proto_rawDescData = protoimpl.X.CompressGZIP(file_ccmy_ccmy_proto_rawDescData)
	})
	return file_ccmy_ccmy_proto_rawDescData
}

var file_ccmy_ccmy_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ccmy_ccmy_proto_goTypes = []interface{}{
	(*RequestReq)(nil),         // 0: ccmy.RequestReq
	(*GetAllRequestResp)(nil),  // 1: ccmy.GetAllRequestResp
	(*UInfo)(nil),              // 2: ccmy.UInfo
	(*UpdateUserGroupReq)(nil), // 3: ccmy.UpdateUserGroupReq
	(*AddGroupReq)(nil),        // 4: ccmy.AddGroupReq
	(*AddDocReq)(nil),          // 5: ccmy.AddDocReq
	(*GetStoreResp)(nil),       // 6: ccmy.GetStoreResp
	(*AddReq)(nil),             // 7: ccmy.AddReq
	(*NameResp)(nil),           // 8: ccmy.NameResp
	(*GetAllNameResp)(nil),     // 9: ccmy.GetAllNameResp
	(*SearchReq)(nil),          // 10: ccmy.SearchReq
	(*DocInfo)(nil),            // 11: ccmy.DocInfo
	(*SearchResp)(nil),         // 12: ccmy.SearchResp
	(*common.Empty)(nil),       // 13: common.Empty
}
var file_ccmy_ccmy_proto_depIdxs = []int32{
	2,  // 0: ccmy.GetAllRequestResp.list:type_name -> ccmy.UInfo
	8,  // 1: ccmy.GetAllNameResp.nameResp:type_name -> ccmy.NameResp
	11, // 2: ccmy.SearchResp.docs:type_name -> ccmy.DocInfo
	13, // 3: ccmy.ccmy.GetStore:input_type -> common.Empty
	7,  // 4: ccmy.ccmy.Add:input_type -> ccmy.AddReq
	5,  // 5: ccmy.ccmy.AddDoc:input_type -> ccmy.AddDocReq
	13, // 6: ccmy.ccmy.GetAllName:input_type -> common.Empty
	10, // 7: ccmy.ccmy.Search:input_type -> ccmy.SearchReq
	4,  // 8: ccmy.ccmy.AddGroup:input_type -> ccmy.AddGroupReq
	3,  // 9: ccmy.ccmy.UpdateUserGroup:input_type -> ccmy.UpdateUserGroupReq
	13, // 10: ccmy.ccmy.GetAllRequest:input_type -> common.Empty
	0,  // 11: ccmy.ccmy.Request:input_type -> ccmy.RequestReq
	6,  // 12: ccmy.ccmy.GetStore:output_type -> ccmy.GetStoreResp
	13, // 13: ccmy.ccmy.Add:output_type -> common.Empty
	13, // 14: ccmy.ccmy.AddDoc:output_type -> common.Empty
	9,  // 15: ccmy.ccmy.GetAllName:output_type -> ccmy.GetAllNameResp
	12, // 16: ccmy.ccmy.Search:output_type -> ccmy.SearchResp
	13, // 17: ccmy.ccmy.AddGroup:output_type -> common.Empty
	13, // 18: ccmy.ccmy.UpdateUserGroup:output_type -> common.Empty
	1,  // 19: ccmy.ccmy.GetAllRequest:output_type -> ccmy.GetAllRequestResp
	13, // 20: ccmy.ccmy.Request:output_type -> common.Empty
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_ccmy_ccmy_proto_init() }
func file_ccmy_ccmy_proto_init() {
	if File_ccmy_ccmy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ccmy_ccmy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRequestResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDocReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStoreResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllNameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccmy_ccmy_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ccmy_ccmy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ccmy_ccmy_proto_goTypes,
		DependencyIndexes: file_ccmy_ccmy_proto_depIdxs,
		MessageInfos:      file_ccmy_ccmy_proto_msgTypes,
	}.Build()
	File_ccmy_ccmy_proto = out.File
	file_ccmy_ccmy_proto_rawDesc = nil
	file_ccmy_ccmy_proto_goTypes = nil
	file_ccmy_ccmy_proto_depIdxs = nil
}
